import { describe, expect, it } from "@effect/vitest";
import * as hegel from "@hegeldev/hegel";
import * as gs from "@hegeldev/hegel/generators";
import type { CanonicalMessageRecord } from "@mailmon/core";

import {
  normalizeLabelIds,
  toMessageInsert,
  toMessageUpdateSet,
} from "./canonical-state-mappers.js";
import {
  createMessageCreatedMailboxEvent,
  createMessageUpdatedMailboxEvent,
} from "./mailbox-event-mappers.js";

const hegelSettings = {
  testCases: 40,
};

const labelIdGen = gs.sampledFrom([
  "INBOX",
  "UNREAD",
  "STARRED",
  "IMPORTANT",
  "CATEGORY_PROMOTIONS",
  "Label/custom",
]);

const canonicalMessage = (labelIds: ReadonlyArray<string>): CanonicalMessageRecord => ({
  id: "msg_property",
  threadId: "thr_property",
  providerMessageId: "gmail_msg_property",
  providerThreadId: "gmail_thread_property",
  subject: "Property message",
  from: {
    email: "hello@mailmon.dev",
    name: "Mailmon",
  },
  snippet: "Generated by Hegel",
  receivedAt: "2026-03-24T00:00:00.000Z",
  labelIds,
});

describe("Canonical state mapper properties", () => {
  it(
    "normalizes generated label IDs consistently for rows and mailbox events",
    () =>
      hegel.test((tc) => {
        const labelIds = tc.draw(gs.arrays(labelIdGen, { maxSize: 12 }));
        // oxlint-disable-next-line unicorn/no-array-sort -- sorting a fresh array keeps the expected model independent from normalizeLabelIds while supporting the package test lib.
        const expected = [...new Set(labelIds)].sort();
        const message = canonicalMessage(labelIds);
        const messageCreated = createMessageCreatedMailboxEvent({
          syncRunId: "sync_property",
          occurredAt: "2026-03-24T00:00:00.000Z",
          workspaceId: "ws_property",
          tenantExternalId: "tenant_property",
          mailboxId: "mbx_property",
          message,
        });
        const messageUpdated = createMessageUpdatedMailboxEvent({
          syncRunId: "sync_property",
          occurredAt: "2026-03-24T00:00:00.000Z",
          workspaceId: "ws_property",
          tenantExternalId: "tenant_property",
          mailboxId: "mbx_property",
          message,
        });

        expect(normalizeLabelIds(labelIds)).toEqual(expected);
        expect(toMessageInsert("mbx_property", message).labelIds).toEqual(expected);
        expect(toMessageUpdateSet(message).labelIds).toEqual(expected);

        if (!("labelIds" in messageCreated.data) || !("labelIds" in messageUpdated.data)) {
          throw new Error("message event data did not include label IDs");
        }

        expect(messageCreated.data.labelIds).toEqual(expected);
        expect(messageUpdated.data.labelIds).toEqual(expected);
      }, hegelSettings),
    60_000,
  );
});
