packages:
  - apps/*
  - packages/*

catalog:
  "@effect/cli": ^0.75.0
  "@effect/language-service": ^0.83.1
  "@effect/platform-node": ^0.106.0
  "@google-cloud/tasks": ^6.2.1
  "@types/node": ^25.5.0
  "@varlock/google-secret-manager-plugin": ^0.2.1
  effect: ^3.21.0
  typescript: ^6.0.2
  varlock: ^0.9.1
enableGlobalVirtualStore: true

engineStrict: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - msgpackr-extract
  - protobufjs

packageExtensions:
  drizzle-kit:
    dependencies:
      drizzle-orm: "*"
      postgres: "*"
packageManagerStrictVersion: true
verifyDepsBeforeRun: error
