packages:
  - apps/*
  - packages/*
  - sdks/*

catalog:
  "@effect/language-service": ^0.85.1
  "@effect/platform-node": 4.0.0-beta.65
  "@effect/vitest": 4.0.0-beta.65
  "@google-cloud/pubsub": ^5.3.0
  "@google-cloud/tasks": ^6.2.2
  "@types/node": ^25.7.0
  "@varlock/google-secret-manager-plugin": ^1.1.0
  effect: 4.0.0-beta.65
  google-auth-library: ^10.6.2
  typescript: ^6.0.3
  varlock: ^1.1.0
enableGlobalVirtualStore: true

engineStrict: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@scarf/scarf"
  - esbuild
  - msgpackr-extract
  - protobufjs

packageExtensions:
  drizzle-kit:
    dependencies:
      drizzle-orm: "*"
      postgres: "*"
packageManagerStrictVersion: true
verifyDepsBeforeRun: error
