/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a62481d0c2b3
 */

import { replaysCreate } from "../funcs/replays-create.js";
import { replaysGetById } from "../funcs/replays-get-by-id.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Replays extends ClientSDK {
  /**
   * Create a mailbox event replay
   */
  async create(
    request: models.CreateReplayRequest,
    options?: RequestOptions,
  ): Promise<models.Replay> {
    return unwrapAsync(replaysCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a replay
   */
  async getById(
    request: operations.ReplaysGetRequest,
    options?: RequestOptions,
  ): Promise<models.Replay> {
    return unwrapAsync(replaysGetById(
      this,
      request,
      options,
    ));
  }
}
