/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { MailmonError } from "./mailmon-error.js";

/**
 * Mailbox not found
 */
export type GetV1MailboxesByMailboxIdNotFoundErrorData = {
  type: string;
  title: string;
  status: number;
  code: string;
  detail: string;
  resource?: { [k: string]: string } | undefined;
  retryable: boolean;
};

/**
 * Mailbox not found
 */
export class GetV1MailboxesByMailboxIdNotFoundError extends MailmonError {
  type: string;
  title: string;
  status: number;
  code: string;
  detail: string;
  resource?: { [k: string]: string } | undefined;
  retryable: boolean;

  /** The original data that was passed to this error instance. */
  data$: GetV1MailboxesByMailboxIdNotFoundErrorData;

  constructor(
    err: GetV1MailboxesByMailboxIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.title = err.title;
    this.status = err.status;
    this.code = err.code;
    this.detail = err.detail;
    if (err.resource != null) this.resource = err.resource;
    this.retryable = err.retryable;

    this.name = "GetV1MailboxesByMailboxIdNotFoundError";
  }
}

/**
 * Invalid request
 */
export type GetV1MailboxesByMailboxIdBadRequestErrorData = {
  type: string;
  title: string;
  status: number;
  code: string;
  detail: string;
  resource?: { [k: string]: string } | undefined;
  retryable: boolean;
};

/**
 * Invalid request
 */
export class GetV1MailboxesByMailboxIdBadRequestError extends MailmonError {
  type: string;
  title: string;
  status: number;
  code: string;
  detail: string;
  resource?: { [k: string]: string } | undefined;
  retryable: boolean;

  /** The original data that was passed to this error instance. */
  data$: GetV1MailboxesByMailboxIdBadRequestErrorData;

  constructor(
    err: GetV1MailboxesByMailboxIdBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.title = err.title;
    this.status = err.status;
    this.code = err.code;
    this.detail = err.detail;
    if (err.resource != null) this.resource = err.resource;
    this.retryable = err.retryable;

    this.name = "GetV1MailboxesByMailboxIdBadRequestError";
  }
}

/** @internal */
export const GetV1MailboxesByMailboxIdNotFoundError$inboundSchema:
  z.ZodMiniType<GetV1MailboxesByMailboxIdNotFoundError, unknown> = z.pipe(
    z.object({
      type: types.string(),
      title: types.string(),
      status: types.number(),
      code: types.string(),
      detail: types.string(),
      resource: types.optional(z.record(z.string(), types.string())),
      retryable: types.boolean(),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetV1MailboxesByMailboxIdNotFoundError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetV1MailboxesByMailboxIdBadRequestError$inboundSchema:
  z.ZodMiniType<GetV1MailboxesByMailboxIdBadRequestError, unknown> = z.pipe(
    z.object({
      type: types.string(),
      title: types.string(),
      status: types.number(),
      code: types.string(),
      detail: types.string(),
      resource: types.optional(z.record(z.string(), types.string())),
      retryable: types.boolean(),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetV1MailboxesByMailboxIdBadRequestError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
