/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { MailmonError } from "./mailmon-error.js";

/**
 * Mailbox or webhook endpoint not found
 */
export type PostV1WebhookEndpointsByEndpointIdSubscriptionsNotFoundErrorData = {
  type: string;
  title: string;
  status: number;
  code: string;
  detail: string;
  resource?: { [k: string]: string } | undefined;
  retryable: boolean;
};

/**
 * Mailbox or webhook endpoint not found
 */
export class PostV1WebhookEndpointsByEndpointIdSubscriptionsNotFoundError
  extends MailmonError
{
  type: string;
  title: string;
  status: number;
  code: string;
  detail: string;
  resource?: { [k: string]: string } | undefined;
  retryable: boolean;

  /** The original data that was passed to this error instance. */
  data$: PostV1WebhookEndpointsByEndpointIdSubscriptionsNotFoundErrorData;

  constructor(
    err: PostV1WebhookEndpointsByEndpointIdSubscriptionsNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.title = err.title;
    this.status = err.status;
    this.code = err.code;
    this.detail = err.detail;
    if (err.resource != null) this.resource = err.resource;
    this.retryable = err.retryable;

    this.name = "PostV1WebhookEndpointsByEndpointIdSubscriptionsNotFoundError";
  }
}

/**
 * Invalid request
 */
export type PostV1WebhookEndpointsByEndpointIdSubscriptionsBadRequestErrorData =
  {
    type: string;
    title: string;
    status: number;
    code: string;
    detail: string;
    resource?: { [k: string]: string } | undefined;
    retryable: boolean;
  };

/**
 * Invalid request
 */
export class PostV1WebhookEndpointsByEndpointIdSubscriptionsBadRequestError
  extends MailmonError
{
  type: string;
  title: string;
  status: number;
  code: string;
  detail: string;
  resource?: { [k: string]: string } | undefined;
  retryable: boolean;

  /** The original data that was passed to this error instance. */
  data$: PostV1WebhookEndpointsByEndpointIdSubscriptionsBadRequestErrorData;

  constructor(
    err: PostV1WebhookEndpointsByEndpointIdSubscriptionsBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.title = err.title;
    this.status = err.status;
    this.code = err.code;
    this.detail = err.detail;
    if (err.resource != null) this.resource = err.resource;
    this.retryable = err.retryable;

    this.name =
      "PostV1WebhookEndpointsByEndpointIdSubscriptionsBadRequestError";
  }
}

/** @internal */
export const PostV1WebhookEndpointsByEndpointIdSubscriptionsNotFoundError$inboundSchema:
  z.ZodMiniType<
    PostV1WebhookEndpointsByEndpointIdSubscriptionsNotFoundError,
    unknown
  > = z.pipe(
    z.object({
      type: types.string(),
      title: types.string(),
      status: types.number(),
      code: types.string(),
      detail: types.string(),
      resource: types.optional(z.record(z.string(), types.string())),
      retryable: types.boolean(),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new PostV1WebhookEndpointsByEndpointIdSubscriptionsNotFoundError(
        v,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    }),
  );

/** @internal */
export const PostV1WebhookEndpointsByEndpointIdSubscriptionsBadRequestError$inboundSchema:
  z.ZodMiniType<
    PostV1WebhookEndpointsByEndpointIdSubscriptionsBadRequestError,
    unknown
  > = z.pipe(
    z.object({
      type: types.string(),
      title: types.string(),
      status: types.number(),
      code: types.string(),
      detail: types.string(),
      resource: types.optional(z.record(z.string(), types.string())),
      retryable: types.boolean(),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new PostV1WebhookEndpointsByEndpointIdSubscriptionsBadRequestError(
        v,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    }),
  );
