/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { MailmonError } from "./mailmon-error.js";

/**
 * Invalid request
 */
export type BadRequestErrorData = {
  type: string;
  title: string;
  status: number;
  code: string;
  detail: string;
  resource?: { [k: string]: string } | undefined;
  retryable: boolean;
};

/**
 * Invalid request
 */
export class BadRequestError extends MailmonError {
  type: string;
  title: string;
  status: number;
  code: string;
  detail: string;
  resource?: { [k: string]: string } | undefined;
  retryable: boolean;

  /** The original data that was passed to this error instance. */
  data$: BadRequestErrorData;

  constructor(
    err: BadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.title = err.title;
    this.status = err.status;
    this.code = err.code;
    this.detail = err.detail;
    if (err.resource != null) this.resource = err.resource;
    this.retryable = err.retryable;

    this.name = "BadRequestError";
  }
}

/**
 * Mailbox or webhook endpoint not found
 */
export type NotFoundErrorData = {
  type: string;
  title: string;
  status: number;
  code: string;
  detail: string;
  resource?: { [k: string]: string } | undefined;
  retryable: boolean;
};

/**
 * Mailbox or webhook endpoint not found
 */
export class NotFoundError extends MailmonError {
  type: string;
  title: string;
  status: number;
  code: string;
  detail: string;
  resource?: { [k: string]: string } | undefined;
  retryable: boolean;

  /** The original data that was passed to this error instance. */
  data$: NotFoundErrorData;

  constructor(
    err: NotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.title = err.title;
    this.status = err.status;
    this.code = err.code;
    this.detail = err.detail;
    if (err.resource != null) this.resource = err.resource;
    this.retryable = err.retryable;

    this.name = "NotFoundError";
  }
}

/**
 * Overlapping active replay conflict
 */
export type ConflictErrorData = {
  type: string;
  title: string;
  status: number;
  code: string;
  detail: string;
  resource?: { [k: string]: string } | undefined;
  retryable: boolean;
};

/**
 * Overlapping active replay conflict
 */
export class ConflictError extends MailmonError {
  type: string;
  title: string;
  status: number;
  code: string;
  detail: string;
  resource?: { [k: string]: string } | undefined;
  retryable: boolean;

  /** The original data that was passed to this error instance. */
  data$: ConflictErrorData;

  constructor(
    err: ConflictErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.title = err.title;
    this.status = err.status;
    this.code = err.code;
    this.detail = err.detail;
    if (err.resource != null) this.resource = err.resource;
    this.retryable = err.retryable;

    this.name = "ConflictError";
  }
}

/** @internal */
export const BadRequestError$inboundSchema: z.ZodMiniType<
  BadRequestError,
  unknown
> = z.pipe(
  z.object({
    type: types.string(),
    title: types.string(),
    status: types.number(),
    code: types.string(),
    detail: types.string(),
    resource: types.optional(z.record(z.string(), types.string())),
    retryable: types.boolean(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new BadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const NotFoundError$inboundSchema: z.ZodMiniType<
  NotFoundError,
  unknown
> = z.pipe(
  z.object({
    type: types.string(),
    title: types.string(),
    status: types.number(),
    code: types.string(),
    detail: types.string(),
    resource: types.optional(z.record(z.string(), types.string())),
    retryable: types.boolean(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new NotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const ConflictError$inboundSchema: z.ZodMiniType<
  ConflictError,
  unknown
> = z.pipe(
  z.object({
    type: types.string(),
    title: types.string(),
    status: types.number(),
    code: types.string(),
    detail: types.string(),
    resource: types.optional(z.record(z.string(), types.string())),
    retryable: types.boolean(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ConflictError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
