/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { MailmonError } from "./mailmon-error.js";

export type ProblemDetailsErrorData = {
  type: string;
  title: string;
  status: number;
  code: string;
  detail: string;
  resource?: { [k: string]: string } | undefined;
  retryable: boolean;
};

export class ProblemDetailsError extends MailmonError {
  type: string;
  title: string;
  status: number;
  code: string;
  detail: string;
  resource?: { [k: string]: string } | undefined;
  retryable: boolean;

  /** The original data that was passed to this error instance. */
  data$: ProblemDetailsErrorData;

  constructor(
    err: ProblemDetailsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.title = err.title;
    this.status = err.status;
    this.code = err.code;
    this.detail = err.detail;
    if (err.resource != null) this.resource = err.resource;
    this.retryable = err.retryable;

    this.name = "ProblemDetailsError";
  }
}

/** @internal */
export const ProblemDetailsError$inboundSchema: z.ZodMiniType<
  ProblemDetailsError,
  unknown
> = z.pipe(
  z.object({
    type: types.string(),
    title: types.string(),
    status: types.number(),
    code: types.string(),
    detail: types.string(),
    resource: types.optional(z.record(z.string(), types.string())),
    retryable: types.boolean(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ProblemDetailsError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
