"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetV1ReplaysByReplayIdResponse = void 0;
var GetV1ReplaysByReplayIdResponse;
(function (GetV1ReplaysByReplayIdResponse) {
    GetV1ReplaysByReplayIdResponse.Object_ = {
        Replay: "replay",
    };
    GetV1ReplaysByReplayIdResponse.Status = {
        Queued: "queued",
        Running: "running",
        Completed: "completed",
        Failed: "failed",
        Cancelled: "cancelled",
    };
})(GetV1ReplaysByReplayIdResponse || (exports.GetV1ReplaysByReplayIdResponse = GetV1ReplaysByReplayIdResponse = {}));
