"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetV1MailboxesByMailboxIdResponse = void 0;
var GetV1MailboxesByMailboxIdResponse;
(function (GetV1MailboxesByMailboxIdResponse) {
    GetV1MailboxesByMailboxIdResponse.Object_ = {
        Mailbox: "mailbox",
    };
    GetV1MailboxesByMailboxIdResponse.Provider = {
        Gmail: "gmail",
    };
    GetV1MailboxesByMailboxIdResponse.Status = {
        Active: "active",
        ReconnectRequired: "reconnect_required",
        Disabled: "disabled",
    };
    GetV1MailboxesByMailboxIdResponse.SyncState = {
        Initializing: "initializing",
        Healthy: "healthy",
        Lagging: "lagging",
        Failed: "failed",
    };
    GetV1MailboxesByMailboxIdResponse.WatchState = {
        Active: "active",
        Expiring: "expiring",
        Expired: "expired",
        Unhealthy: "unhealthy",
    };
})(GetV1MailboxesByMailboxIdResponse || (exports.GetV1MailboxesByMailboxIdResponse = GetV1MailboxesByMailboxIdResponse = {}));
