"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetV1ThreadsByThreadIdResponse = void 0;
var GetV1ThreadsByThreadIdResponse;
(function (GetV1ThreadsByThreadIdResponse) {
    GetV1ThreadsByThreadIdResponse.Object_ = {
        Thread: "thread",
    };
})(GetV1ThreadsByThreadIdResponse || (exports.GetV1ThreadsByThreadIdResponse = GetV1ThreadsByThreadIdResponse = {}));
