"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetV1MessagesResponse = void 0;
var GetV1MessagesResponse;
(function (GetV1MessagesResponse) {
    GetV1MessagesResponse.Object_ = {
        List: "list",
    };
})(GetV1MessagesResponse || (exports.GetV1MessagesResponse = GetV1MessagesResponse = {}));
