"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.PostV1MailboxesConnectSessionsResponse = void 0;
var PostV1MailboxesConnectSessionsResponse;
(function (PostV1MailboxesConnectSessionsResponse) {
    PostV1MailboxesConnectSessionsResponse.Object_ = {
        ConnectSession: "connect_session",
    };
})(PostV1MailboxesConnectSessionsResponse || (exports.PostV1MailboxesConnectSessionsResponse = PostV1MailboxesConnectSessionsResponse = {}));
