"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.PostV1WebhookEndpointsByEndpointIdSubscriptionsResponse = void 0;
var PostV1WebhookEndpointsByEndpointIdSubscriptionsResponse;
(function (PostV1WebhookEndpointsByEndpointIdSubscriptionsResponse) {
    PostV1WebhookEndpointsByEndpointIdSubscriptionsResponse.Object_ = {
        List: "list",
    };
    let Data;
    (function (Data) {
        let Item;
        (function (Item_1) {
            Item_1.Object_ = {
                WebhookEndpointSubscription: "webhook_endpoint_subscription",
            };
            let EventTypes;
            (function (EventTypes) {
                EventTypes.Item = {
                    MessageCreated: "message.created",
                    MessageUpdated: "message.updated",
                    ThreadUpdated: "thread.updated",
                };
            })(EventTypes = Item_1.EventTypes || (Item_1.EventTypes = {}));
        })(Item = Data.Item || (Data.Item = {}));
    })(Data = PostV1WebhookEndpointsByEndpointIdSubscriptionsResponse.Data || (PostV1WebhookEndpointsByEndpointIdSubscriptionsResponse.Data = {}));
})(PostV1WebhookEndpointsByEndpointIdSubscriptionsResponse || (exports.PostV1WebhookEndpointsByEndpointIdSubscriptionsResponse = PostV1WebhookEndpointsByEndpointIdSubscriptionsResponse = {}));
