"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.PostV1ReplaysResponse = void 0;
var PostV1ReplaysResponse;
(function (PostV1ReplaysResponse) {
    PostV1ReplaysResponse.Object_ = {
        Replay: "replay",
    };
    PostV1ReplaysResponse.Status = {
        Queued: "queued",
        Running: "running",
        Completed: "completed",
        Failed: "failed",
        Cancelled: "cancelled",
    };
})(PostV1ReplaysResponse || (exports.PostV1ReplaysResponse = PostV1ReplaysResponse = {}));
