"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.PostV1WebhookEndpointsResponse = void 0;
var PostV1WebhookEndpointsResponse;
(function (PostV1WebhookEndpointsResponse) {
    PostV1WebhookEndpointsResponse.Object_ = {
        WebhookEndpoint: "webhook_endpoint",
    };
    PostV1WebhookEndpointsResponse.DeliveryState = {
        Healthy: "healthy",
        Degraded: "degraded",
        Failing: "failing",
    };
})(PostV1WebhookEndpointsResponse || (exports.PostV1WebhookEndpointsResponse = PostV1WebhookEndpointsResponse = {}));
