"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.PostV1MailboxesConnectSessionsRequest = void 0;
var PostV1MailboxesConnectSessionsRequest;
(function (PostV1MailboxesConnectSessionsRequest) {
    PostV1MailboxesConnectSessionsRequest.Provider = {
        Gmail: "gmail",
    };
})(PostV1MailboxesConnectSessionsRequest || (exports.PostV1MailboxesConnectSessionsRequest = PostV1MailboxesConnectSessionsRequest = {}));
