"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.PostV1WebhookEndpointsByEndpointIdSubscriptionsRequest = void 0;
var PostV1WebhookEndpointsByEndpointIdSubscriptionsRequest;
(function (PostV1WebhookEndpointsByEndpointIdSubscriptionsRequest) {
    let EventTypes;
    (function (EventTypes) {
        EventTypes.Item = {
            MessageCreated: "message.created",
            MessageUpdated: "message.updated",
            ThreadUpdated: "thread.updated",
        };
    })(EventTypes = PostV1WebhookEndpointsByEndpointIdSubscriptionsRequest.EventTypes || (PostV1WebhookEndpointsByEndpointIdSubscriptionsRequest.EventTypes = {}));
})(PostV1WebhookEndpointsByEndpointIdSubscriptionsRequest || (exports.PostV1WebhookEndpointsByEndpointIdSubscriptionsRequest = PostV1WebhookEndpointsByEndpointIdSubscriptionsRequest = {}));
