// This file was auto-generated by Fern from our API Definition.
export var PostV1MailboxesConnectSessionsRequest;
(function (PostV1MailboxesConnectSessionsRequest) {
    PostV1MailboxesConnectSessionsRequest.Provider = {
        Gmail: "gmail",
    };
})(PostV1MailboxesConnectSessionsRequest || (PostV1MailboxesConnectSessionsRequest = {}));
