// This file was auto-generated by Fern from our API Definition.
export var PostV1WebhookEndpointsByEndpointIdSubscriptionsRequest;
(function (PostV1WebhookEndpointsByEndpointIdSubscriptionsRequest) {
    let EventTypes;
    (function (EventTypes) {
        EventTypes.Item = {
            MessageCreated: "message.created",
            MessageUpdated: "message.updated",
            ThreadUpdated: "thread.updated",
        };
    })(EventTypes = PostV1WebhookEndpointsByEndpointIdSubscriptionsRequest.EventTypes || (PostV1WebhookEndpointsByEndpointIdSubscriptionsRequest.EventTypes = {}));
})(PostV1WebhookEndpointsByEndpointIdSubscriptionsRequest || (PostV1WebhookEndpointsByEndpointIdSubscriptionsRequest = {}));
