import { describe, expect, it } from "@effect/vitest";
import * as hegel from "@hegeldev/hegel";
import * as gs from "@hegeldev/hegel/generators";

import {
  calculateWebhookDeliveryRetryDelayMs,
  classifyWebhookDeliveryFailure,
  classifyWebhookDeliveryResponse,
} from "./webhook-delivery-execution.js";

const hegelSettings = {
  testCases: 40,
};

const completedAt = "2026-03-24T00:00:10.000Z";
const maxRetryDelayMs = 15 * 60_000;
const maxAttempts = 5;

const deliveryAttempt = (attemptCount: number) => ({
  deliveryId: "del_property",
  attemptCount,
  processingStartedAt: "2026-03-24T00:00:05.000Z",
});

const millisecondsBetween = (left: string, right: string) => Date.parse(left) - Date.parse(right);

const pendingAttemptCountGen = gs.sampledFrom([1, 2, 3, 4]);
const attemptCountBoundaryGen = gs.sampledFrom([0, 1, 2, 3, 4, 5, 6, 8, 10, 12]);
const retryableStatusCodeGen = gs.sampledFrom([500, 502, 503, 504, 599]);
const terminalStatusCodeGen = gs.sampledFrom([
  200, 201, 204, 299, 300, 301, 308, 400, 401, 404, 409, 422, 429,
]);
const terminalOutcomeKindGen = gs.sampledFrom([
  "terminal-response",
  "exhausted-response",
  "nonretryable-failure",
  "exhausted-failure",
] as const);

describe("Webhook delivery execution properties", () => {
  it(
    "keeps retry delay calculation bounded and monotonic",
    () =>
      hegel.test((tc) => {
        const attemptCount = tc.draw(attemptCountBoundaryGen);
        const retryDelayMs = calculateWebhookDeliveryRetryDelayMs(attemptCount);
        const nextRetryDelayMs = calculateWebhookDeliveryRetryDelayMs(attemptCount + 1);

        expect(retryDelayMs).toBeGreaterThanOrEqual(5_000);
        expect(retryDelayMs).toBeLessThanOrEqual(maxRetryDelayMs);
        expect(nextRetryDelayMs).toBeGreaterThanOrEqual(retryDelayMs);
        expect(nextRetryDelayMs).toBeLessThanOrEqual(maxRetryDelayMs);
      }, hegelSettings),
    60_000,
  );

  it(
    "classifies retryable responses before max attempts as bounded pending retries",
    () =>
      hegel.test((tc) => {
        const attemptCount = tc.draw(pendingAttemptCountGen);
        const statusCode = tc.draw(retryableStatusCodeGen);
        const classified = classifyWebhookDeliveryResponse(
          deliveryAttempt(attemptCount),
          completedAt,
          statusCode,
        );

        expect(classified.completion.state).toBe("pending");
        expect(classified.completion.retryable).toBe(true);
        expect(classified.result.status).toBe("scheduled_for_retry");
        expect(classified.result.nextAttemptAt).not.toBeNull();
        expect(classified.completion.nextAttemptAt).toBe(classified.result.nextAttemptAt);

        const nextAttemptAt = classified.result.nextAttemptAt;

        if (nextAttemptAt === null) {
          throw new Error("retryable response did not produce a next attempt");
        }

        const retryDelayMs = millisecondsBetween(nextAttemptAt, completedAt);

        expect(retryDelayMs).toBe(calculateWebhookDeliveryRetryDelayMs(attemptCount));
        expect(retryDelayMs).toBeGreaterThan(0);
        expect(retryDelayMs).toBeLessThanOrEqual(maxRetryDelayMs);
      }, hegelSettings),
    60_000,
  );

  it(
    "classifies retryable sender failures before max attempts as bounded pending retries",
    () =>
      hegel.test((tc) => {
        const attemptCount = tc.draw(pendingAttemptCountGen);
        const failureCode = tc.draw(
          gs.sampledFrom([
            "webhook_delivery_timeout",
            "webhook_delivery_network_error",
            "webhook_delivery_tls_error",
          ]),
        );
        const classified = classifyWebhookDeliveryFailure(
          deliveryAttempt(attemptCount),
          completedAt,
          {
            code: failureCode,
            message: `${failureCode} generated by property test`,
            retryable: true,
          },
        );

        expect(classified.completion.state).toBe("pending");
        expect(classified.completion.retryable).toBe(true);
        expect(classified.result.status).toBe("scheduled_for_retry");
        expect(classified.result.nextAttemptAt).not.toBeNull();
        expect(classified.completion.nextAttemptAt).toBe(classified.result.nextAttemptAt);

        const nextAttemptAt = classified.result.nextAttemptAt;

        if (nextAttemptAt === null) {
          throw new Error("retryable failure did not produce a next attempt");
        }

        const retryDelayMs = millisecondsBetween(nextAttemptAt, completedAt);

        expect(retryDelayMs).toBe(calculateWebhookDeliveryRetryDelayMs(attemptCount));
        expect(retryDelayMs).toBeGreaterThan(0);
        expect(retryDelayMs).toBeLessThanOrEqual(maxRetryDelayMs);
      }, hegelSettings),
    60_000,
  );

  it(
    "never schedules another attempt for terminal webhook outcomes",
    () =>
      hegel.test((tc) => {
        const kind = tc.draw(terminalOutcomeKindGen);
        const classified =
          kind === "terminal-response"
            ? classifyWebhookDeliveryResponse(
                deliveryAttempt(1),
                completedAt,
                tc.draw(terminalStatusCodeGen),
              )
            : kind === "exhausted-response"
              ? classifyWebhookDeliveryResponse(
                  deliveryAttempt(maxAttempts),
                  completedAt,
                  tc.draw(retryableStatusCodeGen),
                )
              : kind === "nonretryable-failure"
                ? classifyWebhookDeliveryFailure(deliveryAttempt(1), completedAt, {
                    code: "webhook_delivery_nonretryable_property_failure",
                    message: "Generated nonretryable sender failure",
                    retryable: false,
                  })
                : classifyWebhookDeliveryFailure(deliveryAttempt(maxAttempts), completedAt, {
                    code: "webhook_delivery_timeout",
                    message: "Generated exhausted sender failure",
                    retryable: true,
                  });

        expect(classified.completion.state).not.toBe("pending");
        expect(classified.completion.nextAttemptAt).toBeNull();
        expect(classified.result.status).not.toBe("scheduled_for_retry");
        expect(classified.result.nextAttemptAt).toBeNull();
      }, hegelSettings),
    60_000,
  );
});
