/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3ff29f98563c
 */

import * as z from "zod/v4-mini";

export type MailboxesGetRequest = {
  mailboxId: string;
};

/** @internal */
export type MailboxesGetRequest$Outbound = {
  mailboxId: string;
};

/** @internal */
export const MailboxesGetRequest$outboundSchema: z.ZodMiniType<
  MailboxesGetRequest$Outbound,
  MailboxesGetRequest
> = z.object({
  mailboxId: z.string(),
});

export function mailboxesGetRequestToJSON(
  mailboxesGetRequest: MailboxesGetRequest,
): string {
  return JSON.stringify(
    MailboxesGetRequest$outboundSchema.parse(mailboxesGetRequest),
  );
}
