/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: da11e6133551
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ThreadsListRequest = {
  cursor?: string | undefined;
  limit?: number | undefined;
  mailboxId: string;
};

export type ThreadsListResponse = {
  result: models.ThreadList;
};

/** @internal */
export type ThreadsListRequest$Outbound = {
  cursor?: string | undefined;
  limit?: number | undefined;
  mailboxId: string;
};

/** @internal */
export const ThreadsListRequest$outboundSchema: z.ZodMiniType<
  ThreadsListRequest$Outbound,
  ThreadsListRequest
> = z.object({
  cursor: z.optional(z.string()),
  limit: z.optional(z.int()),
  mailboxId: z.string(),
});

export function threadsListRequestToJSON(
  threadsListRequest: ThreadsListRequest,
): string {
  return JSON.stringify(
    ThreadsListRequest$outboundSchema.parse(threadsListRequest),
  );
}

/** @internal */
export const ThreadsListResponse$inboundSchema: z.ZodMiniType<
  ThreadsListResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.ThreadList$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function threadsListResponseFromJSON(
  jsonString: string,
): SafeParseResult<ThreadsListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ThreadsListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ThreadsListResponse' from JSON`,
  );
}
