/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mailboxesCreateConnectSession } from "../funcs/mailboxes-create-connect-session.js";
import { mailboxesGetById } from "../funcs/mailboxes-get-by-id.js";
import { mailboxesGetObservability } from "../funcs/mailboxes-get-observability.js";
import { mailboxesListSyncRuns } from "../funcs/mailboxes-list-sync-runs.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Mailboxes extends ClientSDK {
  /**
   * Create a mailbox connect session
   */
  async createConnectSession(
    request: operations.PostV1MailboxesConnectSessionsRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1MailboxesConnectSessionsResponse> {
    return unwrapAsync(mailboxesCreateConnectSession(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a mailbox
   */
  async getById(
    request: operations.GetV1MailboxesByMailboxIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1MailboxesByMailboxIdResponse> {
    return unwrapAsync(mailboxesGetById(
      this,
      request,
      options,
    ));
  }

  /**
   * List mailbox sync runs
   */
  async listSyncRuns(
    request: operations.GetV1MailboxesByMailboxIdSyncRunsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1MailboxesByMailboxIdSyncRunsResponse> {
    return unwrapAsync(mailboxesListSyncRuns(
      this,
      request,
      options,
    ));
  }

  /**
   * Get mailbox observability
   */
  async getObservability(
    request: operations.GetV1MailboxesByMailboxIdObservabilityRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1MailboxesByMailboxIdObservabilityResponse> {
    return unwrapAsync(mailboxesGetObservability(
      this,
      request,
      options,
    ));
  }
}
