/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { messagesGetById } from "../funcs/messages-get-by-id.js";
import { messagesList } from "../funcs/messages-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Messages extends ClientSDK {
  /**
   * List mailbox messages
   */
  async list(
    request: operations.MessagesListRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.MessagesListResponse, { cursor: string }>
  > {
    return unwrapResultIterator(messagesList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a message
   */
  async getById(
    request: operations.MessagesGetRequest,
    options?: RequestOptions,
  ): Promise<models.Message> {
    return unwrapAsync(messagesGetById(
      this,
      request,
      options,
    ));
  }
}
