/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { replaysCreate } from "../funcs/replays-create.js";
import { replaysGetById } from "../funcs/replays-get-by-id.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Replays extends ClientSDK {
  /**
   * Create a mailbox event replay
   */
  async create(
    request: operations.PostV1ReplaysRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1ReplaysResponse> {
    return unwrapAsync(replaysCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a replay
   */
  async getById(
    request: operations.GetV1ReplaysByReplayIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1ReplaysByReplayIdResponse> {
    return unwrapAsync(replaysGetById(
      this,
      request,
      options,
    ));
  }
}
