/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getV1MailboxesByMailboxIdObservability } from "../funcs/get-v1-mailboxes-by-mailbox-id-observability.js";
import { getV1MailboxesByMailboxIdSyncRuns } from "../funcs/get-v1-mailboxes-by-mailbox-id-sync-runs.js";
import { getV1MailboxesByMailboxId } from "../funcs/get-v1-mailboxes-by-mailbox-id.js";
import { getV1MessagesByMessageId } from "../funcs/get-v1-messages-by-message-id.js";
import { getV1Messages } from "../funcs/get-v1-messages.js";
import { getV1ReplaysByReplayId } from "../funcs/get-v1-replays-by-replay-id.js";
import { getV1ThreadsByThreadId } from "../funcs/get-v1-threads-by-thread-id.js";
import { getV1Threads } from "../funcs/get-v1-threads.js";
import { postV1MailboxesConnectSessions } from "../funcs/post-v1-mailboxes-connect-sessions.js";
import { postV1Replays } from "../funcs/post-v1-replays.js";
import { postV1WebhookEndpointsByEndpointIdSubscriptions } from "../funcs/post-v1-webhook-endpoints-by-endpoint-id-subscriptions.js";
import { postV1WebhookEndpoints } from "../funcs/post-v1-webhook-endpoints.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Mailmon extends ClientSDK {
  /**
   * Create a mailbox connect session
   */
  async postV1MailboxesConnectSessions(
    request: operations.PostV1MailboxesConnectSessionsRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1MailboxesConnectSessionsResponse> {
    return unwrapAsync(postV1MailboxesConnectSessions(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a webhook endpoint
   */
  async postV1WebhookEndpoints(
    request: operations.PostV1WebhookEndpointsRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1WebhookEndpointsResponse> {
    return unwrapAsync(postV1WebhookEndpoints(
      this,
      request,
      options,
    ));
  }

  /**
   * Create mailbox-scoped webhook subscriptions
   */
  async postV1WebhookEndpointsByEndpointIdSubscriptions(
    request: operations.PostV1WebhookEndpointsByEndpointIdSubscriptionsRequest,
    options?: RequestOptions,
  ): Promise<
    operations.PostV1WebhookEndpointsByEndpointIdSubscriptionsResponse
  > {
    return unwrapAsync(postV1WebhookEndpointsByEndpointIdSubscriptions(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a mailbox
   */
  async getV1MailboxesByMailboxId(
    request: operations.GetV1MailboxesByMailboxIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1MailboxesByMailboxIdResponse> {
    return unwrapAsync(getV1MailboxesByMailboxId(
      this,
      request,
      options,
    ));
  }

  /**
   * List mailbox sync runs
   */
  async getV1MailboxesByMailboxIdSyncRuns(
    request: operations.GetV1MailboxesByMailboxIdSyncRunsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1MailboxesByMailboxIdSyncRunsResponse> {
    return unwrapAsync(getV1MailboxesByMailboxIdSyncRuns(
      this,
      request,
      options,
    ));
  }

  /**
   * Get mailbox observability
   */
  async getV1MailboxesByMailboxIdObservability(
    request: operations.GetV1MailboxesByMailboxIdObservabilityRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1MailboxesByMailboxIdObservabilityResponse> {
    return unwrapAsync(getV1MailboxesByMailboxIdObservability(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a mailbox event replay
   */
  async postV1Replays(
    request: operations.PostV1ReplaysRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1ReplaysResponse> {
    return unwrapAsync(postV1Replays(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a replay
   */
  async getV1ReplaysByReplayId(
    request: operations.GetV1ReplaysByReplayIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1ReplaysByReplayIdResponse> {
    return unwrapAsync(getV1ReplaysByReplayId(
      this,
      request,
      options,
    ));
  }

  /**
   * List mailbox messages
   */
  async getV1Messages(
    request: operations.GetV1MessagesRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1MessagesResponse> {
    return unwrapAsync(getV1Messages(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a message
   */
  async getV1MessagesByMessageId(
    request: operations.GetV1MessagesByMessageIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1MessagesByMessageIdResponse> {
    return unwrapAsync(getV1MessagesByMessageId(
      this,
      request,
      options,
    ));
  }

  /**
   * List mailbox threads
   */
  async getV1Threads(
    request: operations.GetV1ThreadsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1ThreadsResponse> {
    return unwrapAsync(getV1Threads(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a thread
   */
  async getV1ThreadsByThreadId(
    request: operations.GetV1ThreadsByThreadIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1ThreadsByThreadIdResponse> {
    return unwrapAsync(getV1ThreadsByThreadId(
      this,
      request,
      options,
    ));
  }
}
