/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8e32891c47cc
 */

import { ClientSDK } from "../lib/sdks.js";
import { Mailboxes } from "./mailboxes.js";
import { Messages } from "./messages.js";
import { Replays } from "./replays.js";
import { Threads } from "./threads.js";
import { WebhookEndpoints } from "./webhook-endpoints.js";

export class Mailmon extends ClientSDK {
  private _mailboxes?: Mailboxes;
  get mailboxes(): Mailboxes {
    return (this._mailboxes ??= new Mailboxes(this._options));
  }

  private _webhookEndpoints?: WebhookEndpoints;
  get webhookEndpoints(): WebhookEndpoints {
    return (this._webhookEndpoints ??= new WebhookEndpoints(this._options));
  }

  private _replays?: Replays;
  get replays(): Replays {
    return (this._replays ??= new Replays(this._options));
  }

  private _messages?: Messages;
  get messages(): Messages {
    return (this._messages ??= new Messages(this._options));
  }

  private _threads?: Threads;
  get threads(): Threads {
    return (this._threads ??= new Threads(this._options));
  }
}
