/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { threadsGetById } from "../funcs/threads-get-by-id.js";
import { threadsList } from "../funcs/threads-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Threads extends ClientSDK {
  /**
   * List mailbox threads
   */
  async list(
    request: operations.ThreadsListRequest,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ThreadsListResponse, { cursor: string }>> {
    return unwrapResultIterator(threadsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a thread
   */
  async getById(
    request: operations.ThreadsGetRequest,
    options?: RequestOptions,
  ): Promise<models.Thread> {
    return unwrapAsync(threadsGetById(
      this,
      request,
      options,
    ));
  }
}
