/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { threadsGetById } from "../funcs/threads-get-by-id.js";
import { threadsList } from "../funcs/threads-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Threads extends ClientSDK {
  /**
   * List mailbox threads
   */
  async list(
    request: operations.GetV1ThreadsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1ThreadsResponse> {
    return unwrapAsync(threadsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a thread
   */
  async getById(
    request: operations.GetV1ThreadsByThreadIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1ThreadsByThreadIdResponse> {
    return unwrapAsync(threadsGetById(
      this,
      request,
      options,
    ));
  }
}
