/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhookEndpointsCreateSubscription } from "../funcs/webhook-endpoints-create-subscription.js";
import { webhookEndpointsCreate } from "../funcs/webhook-endpoints-create.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class WebhookEndpoints extends ClientSDK {
  /**
   * Create a webhook endpoint
   */
  async create(
    request: operations.PostV1WebhookEndpointsRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1WebhookEndpointsResponse> {
    return unwrapAsync(webhookEndpointsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Create mailbox-scoped webhook subscriptions
   */
  async createSubscription(
    request: operations.PostV1WebhookEndpointsByEndpointIdSubscriptionsRequest,
    options?: RequestOptions,
  ): Promise<
    operations.PostV1WebhookEndpointsByEndpointIdSubscriptionsResponse
  > {
    return unwrapAsync(webhookEndpointsCreateSubscription(
      this,
      request,
      options,
    ));
  }
}
