/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 07d1a27ecf24
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const MessageListObject = {
  List: "list",
} as const;
export type MessageListObject = ClosedEnum<typeof MessageListObject>;

export type MessageListFrom = {
  name: string | null;
  email: string;
};

export type MessageListData = {
  id: string;
  mailboxId: string;
  threadId: string;
  providerMessageId: string;
  subject: string;
  from: MessageListFrom;
  snippet: string;
  receivedAt: Date;
  labelIds: Array<string>;
};

export type MessageList = {
  object: MessageListObject;
  data: Array<MessageListData>;
  nextCursor: string | null;
};

/** @internal */
export const MessageListObject$inboundSchema: z.ZodMiniEnum<
  typeof MessageListObject
> = z.enum(MessageListObject);

/** @internal */
export const MessageListFrom$inboundSchema: z.ZodMiniType<
  MessageListFrom,
  unknown
> = z.object({
  name: types.nullable(types.string()),
  email: types.string(),
});

export function messageListFromFromJSON(
  jsonString: string,
): SafeParseResult<MessageListFrom, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MessageListFrom$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MessageListFrom' from JSON`,
  );
}

/** @internal */
export const MessageListData$inboundSchema: z.ZodMiniType<
  MessageListData,
  unknown
> = z.object({
  id: types.string(),
  mailboxId: types.string(),
  threadId: types.string(),
  providerMessageId: types.string(),
  subject: types.string(),
  from: z.lazy(() => MessageListFrom$inboundSchema),
  snippet: types.string(),
  receivedAt: types.date(),
  labelIds: z.array(types.string()),
});

export function messageListDataFromJSON(
  jsonString: string,
): SafeParseResult<MessageListData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MessageListData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MessageListData' from JSON`,
  );
}

/** @internal */
export const MessageList$inboundSchema: z.ZodMiniType<MessageList, unknown> = z
  .object({
    object: MessageListObject$inboundSchema,
    data: z.array(z.lazy(() => MessageListData$inboundSchema)),
    nextCursor: types.nullable(types.string()),
  });

export function messageListFromJSON(
  jsonString: string,
): SafeParseResult<MessageList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MessageList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MessageList' from JSON`,
  );
}
