/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2076f3d5e3ad
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  SyncRunStatus,
  SyncRunStatus$inboundSchema,
} from "./sync-run-status.js";

export type SyncRun = {
  syncRunId: string;
  mailboxId: string;
  startedAt: Date;
  completedAt: Date | null;
  status: SyncRunStatus;
  detail: string | null;
  eventsEmitted: number | null;
  leaseOwnerId: string | null;
  previousCursor: string | null;
  nextCursor: string | null;
  cursorAdvanced: boolean | null;
};

/** @internal */
export const SyncRun$inboundSchema: z.ZodMiniType<SyncRun, unknown> = z.object({
  syncRunId: types.string(),
  mailboxId: types.string(),
  startedAt: types.date(),
  completedAt: types.nullable(types.date()),
  status: SyncRunStatus$inboundSchema,
  detail: types.nullable(types.string()),
  eventsEmitted: types.nullable(types.number()),
  leaseOwnerId: types.nullable(types.string()),
  previousCursor: types.nullable(types.string()),
  nextCursor: types.nullable(types.string()),
  cursorAdvanced: types.nullable(types.boolean()),
});

export function syncRunFromJSON(
  jsonString: string,
): SafeParseResult<SyncRun, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SyncRun$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SyncRun' from JSON`,
  );
}
