/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f30509b918ca
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const SyncState = {
  Initializing: "initializing",
  Healthy: "healthy",
  Lagging: "lagging",
  Failed: "failed",
} as const;
export type SyncState = OpenEnum<typeof SyncState>;

/** @internal */
export const SyncState$inboundSchema: z.ZodMiniType<SyncState, unknown> =
  openEnums.inboundSchema(SyncState);
