/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8358635eb1ca
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DeliveryState,
  DeliveryState$inboundSchema,
} from "./delivery-state.js";
import { ErrorDetail, ErrorDetail$inboundSchema } from "./error-detail.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const WebhookEndpointObject = {
  WebhookEndpoint: "webhook_endpoint",
} as const;
export type WebhookEndpointObject = ClosedEnum<typeof WebhookEndpointObject>;

export type WebhookEndpoint = {
  id: string;
  object: WebhookEndpointObject;
  url: string;
  description: string | null;
  deliveryState: DeliveryState;
  lastDeliveryAt: Date | null;
  lastDeliveryError: ErrorDetail | null;
  createdAt: Date;
  secret: string;
};

/** @internal */
export const WebhookEndpointObject$inboundSchema: z.ZodMiniEnum<
  typeof WebhookEndpointObject
> = z.enum(WebhookEndpointObject);

/** @internal */
export const WebhookEndpoint$inboundSchema: z.ZodMiniType<
  WebhookEndpoint,
  unknown
> = z.object({
  id: types.string(),
  object: WebhookEndpointObject$inboundSchema,
  url: types.string(),
  description: types.nullable(types.string()),
  deliveryState: DeliveryState$inboundSchema,
  lastDeliveryAt: types.nullable(types.date()),
  lastDeliveryError: types.nullable(ErrorDetail$inboundSchema),
  createdAt: types.date(),
  secret: types.string(),
});

export function webhookEndpointFromJSON(
  jsonString: string,
): SafeParseResult<WebhookEndpoint, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookEndpoint$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookEndpoint' from JSON`,
  );
}
