/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8a44bd2d2268
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @mailmon.dev/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx mailboxesCreateConnectSession.example.ts
 */

import { Mailmon } from "@mailmon.dev/sdk";

const mailmon = new Mailmon({
  bearerAuth: process.env["MAILMON_BEARER_AUTH"] ?? "",
});

async function main() {
  const result = await mailmon.mailboxes.createConnectSession({
    provider: "gmail",
    tenantExternalId: "<id>",
    mailboxExternalId: "<id>",
    redirectUrl: "https://courteous-valley.name",
  });

  console.log(result);
}

main().catch(console.error);
