/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetV1MessagesRequest = {
  cursor?: string | undefined;
  limit?: number | undefined;
  mailboxId: string;
};

export const GetV1MessagesObject = {
  List: "list",
} as const;
export type GetV1MessagesObject = ClosedEnum<typeof GetV1MessagesObject>;

/**
 * Mailbox messages
 */
export type GetV1MessagesResponse = {
  object: GetV1MessagesObject;
  data: Array<models.Message>;
  nextCursor: string | null;
};

/** @internal */
export type GetV1MessagesRequest$Outbound = {
  cursor?: string | undefined;
  limit?: number | undefined;
  mailboxId: string;
};

/** @internal */
export const GetV1MessagesRequest$outboundSchema: z.ZodMiniType<
  GetV1MessagesRequest$Outbound,
  GetV1MessagesRequest
> = z.object({
  cursor: z.optional(z.string()),
  limit: z.optional(z.int()),
  mailboxId: z.string(),
});

export function getV1MessagesRequestToJSON(
  getV1MessagesRequest: GetV1MessagesRequest,
): string {
  return JSON.stringify(
    GetV1MessagesRequest$outboundSchema.parse(getV1MessagesRequest),
  );
}

/** @internal */
export const GetV1MessagesObject$inboundSchema: z.ZodMiniEnum<
  typeof GetV1MessagesObject
> = z.enum(GetV1MessagesObject);

/** @internal */
export const GetV1MessagesResponse$inboundSchema: z.ZodMiniType<
  GetV1MessagesResponse,
  unknown
> = z.object({
  object: GetV1MessagesObject$inboundSchema,
  data: z.array(models.Message$inboundSchema),
  nextCursor: types.nullable(types.string()),
});

export function getV1MessagesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1MessagesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1MessagesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1MessagesResponse' from JSON`,
  );
}
