/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetV1MailboxesByMailboxIdSyncRunsRequest = {
  cursor?: string | undefined;
  limit?: number | undefined;
  mailboxId: string;
};

export const GetV1MailboxesByMailboxIdSyncRunsObject = {
  List: "list",
} as const;
export type GetV1MailboxesByMailboxIdSyncRunsObject = ClosedEnum<
  typeof GetV1MailboxesByMailboxIdSyncRunsObject
>;

/**
 * Mailbox sync runs
 */
export type GetV1MailboxesByMailboxIdSyncRunsResponse = {
  object: GetV1MailboxesByMailboxIdSyncRunsObject;
  data: Array<models.SyncRun>;
  nextCursor: string | null;
};

/** @internal */
export type GetV1MailboxesByMailboxIdSyncRunsRequest$Outbound = {
  cursor?: string | undefined;
  limit?: number | undefined;
  mailboxId: string;
};

/** @internal */
export const GetV1MailboxesByMailboxIdSyncRunsRequest$outboundSchema:
  z.ZodMiniType<
    GetV1MailboxesByMailboxIdSyncRunsRequest$Outbound,
    GetV1MailboxesByMailboxIdSyncRunsRequest
  > = z.object({
    cursor: z.optional(z.string()),
    limit: z.optional(z.int()),
    mailboxId: z.string(),
  });

export function getV1MailboxesByMailboxIdSyncRunsRequestToJSON(
  getV1MailboxesByMailboxIdSyncRunsRequest:
    GetV1MailboxesByMailboxIdSyncRunsRequest,
): string {
  return JSON.stringify(
    GetV1MailboxesByMailboxIdSyncRunsRequest$outboundSchema.parse(
      getV1MailboxesByMailboxIdSyncRunsRequest,
    ),
  );
}

/** @internal */
export const GetV1MailboxesByMailboxIdSyncRunsObject$inboundSchema:
  z.ZodMiniEnum<typeof GetV1MailboxesByMailboxIdSyncRunsObject> = z.enum(
    GetV1MailboxesByMailboxIdSyncRunsObject,
  );

/** @internal */
export const GetV1MailboxesByMailboxIdSyncRunsResponse$inboundSchema:
  z.ZodMiniType<GetV1MailboxesByMailboxIdSyncRunsResponse, unknown> = z.object({
    object: GetV1MailboxesByMailboxIdSyncRunsObject$inboundSchema,
    data: z.array(models.SyncRun$inboundSchema),
    nextCursor: types.nullable(types.string()),
  });

export function getV1MailboxesByMailboxIdSyncRunsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1MailboxesByMailboxIdSyncRunsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1MailboxesByMailboxIdSyncRunsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1MailboxesByMailboxIdSyncRunsResponse' from JSON`,
  );
}
