/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetV1MailboxesByMailboxIdRequest = {
  mailboxId: string;
};

export const GetV1MailboxesByMailboxIdObject = {
  Mailbox: "mailbox",
} as const;
export type GetV1MailboxesByMailboxIdObject = ClosedEnum<
  typeof GetV1MailboxesByMailboxIdObject
>;

export const GetV1MailboxesByMailboxIdProvider = {
  Gmail: "gmail",
} as const;
export type GetV1MailboxesByMailboxIdProvider = ClosedEnum<
  typeof GetV1MailboxesByMailboxIdProvider
>;

/**
 * Mailbox
 */
export type GetV1MailboxesByMailboxIdResponse = {
  id: string;
  object: GetV1MailboxesByMailboxIdObject;
  provider: GetV1MailboxesByMailboxIdProvider;
  emailAddress: string;
  status: models.MailboxStatus;
  syncState: models.SyncState;
  watchState: models.WatchState;
  initializedAt: Date | null;
  lastSuccessfulSyncAt: Date | null;
  lastError: models.ErrorDetail | null;
};

/** @internal */
export type GetV1MailboxesByMailboxIdRequest$Outbound = {
  mailboxId: string;
};

/** @internal */
export const GetV1MailboxesByMailboxIdRequest$outboundSchema: z.ZodMiniType<
  GetV1MailboxesByMailboxIdRequest$Outbound,
  GetV1MailboxesByMailboxIdRequest
> = z.object({
  mailboxId: z.string(),
});

export function getV1MailboxesByMailboxIdRequestToJSON(
  getV1MailboxesByMailboxIdRequest: GetV1MailboxesByMailboxIdRequest,
): string {
  return JSON.stringify(
    GetV1MailboxesByMailboxIdRequest$outboundSchema.parse(
      getV1MailboxesByMailboxIdRequest,
    ),
  );
}

/** @internal */
export const GetV1MailboxesByMailboxIdObject$inboundSchema: z.ZodMiniEnum<
  typeof GetV1MailboxesByMailboxIdObject
> = z.enum(GetV1MailboxesByMailboxIdObject);

/** @internal */
export const GetV1MailboxesByMailboxIdProvider$inboundSchema: z.ZodMiniEnum<
  typeof GetV1MailboxesByMailboxIdProvider
> = z.enum(GetV1MailboxesByMailboxIdProvider);

/** @internal */
export const GetV1MailboxesByMailboxIdResponse$inboundSchema: z.ZodMiniType<
  GetV1MailboxesByMailboxIdResponse,
  unknown
> = z.object({
  id: types.string(),
  object: GetV1MailboxesByMailboxIdObject$inboundSchema,
  provider: GetV1MailboxesByMailboxIdProvider$inboundSchema,
  emailAddress: types.string(),
  status: models.MailboxStatus$inboundSchema,
  syncState: models.SyncState$inboundSchema,
  watchState: models.WatchState$inboundSchema,
  initializedAt: types.nullable(types.date()),
  lastSuccessfulSyncAt: types.nullable(types.date()),
  lastError: types.nullable(models.ErrorDetail$inboundSchema),
});

export function getV1MailboxesByMailboxIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1MailboxesByMailboxIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1MailboxesByMailboxIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1MailboxesByMailboxIdResponse' from JSON`,
  );
}
