/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1MessagesByMessageIdRequest = {
  messageId: string;
};

export type GetV1MessagesByMessageIdFrom = {
  name: string | null;
  email: string;
};

/**
 * Message
 */
export type GetV1MessagesByMessageIdResponse = {
  id: string;
  mailboxId: string;
  threadId: string;
  providerMessageId: string;
  subject: string;
  from: GetV1MessagesByMessageIdFrom;
  snippet: string;
  receivedAt: Date;
  labelIds: Array<string>;
};

/** @internal */
export type GetV1MessagesByMessageIdRequest$Outbound = {
  messageId: string;
};

/** @internal */
export const GetV1MessagesByMessageIdRequest$outboundSchema: z.ZodMiniType<
  GetV1MessagesByMessageIdRequest$Outbound,
  GetV1MessagesByMessageIdRequest
> = z.object({
  messageId: z.string(),
});

export function getV1MessagesByMessageIdRequestToJSON(
  getV1MessagesByMessageIdRequest: GetV1MessagesByMessageIdRequest,
): string {
  return JSON.stringify(
    GetV1MessagesByMessageIdRequest$outboundSchema.parse(
      getV1MessagesByMessageIdRequest,
    ),
  );
}

/** @internal */
export const GetV1MessagesByMessageIdFrom$inboundSchema: z.ZodMiniType<
  GetV1MessagesByMessageIdFrom,
  unknown
> = z.object({
  name: types.nullable(types.string()),
  email: types.string(),
});

export function getV1MessagesByMessageIdFromFromJSON(
  jsonString: string,
): SafeParseResult<GetV1MessagesByMessageIdFrom, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1MessagesByMessageIdFrom$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1MessagesByMessageIdFrom' from JSON`,
  );
}

/** @internal */
export const GetV1MessagesByMessageIdResponse$inboundSchema: z.ZodMiniType<
  GetV1MessagesByMessageIdResponse,
  unknown
> = z.object({
  id: types.string(),
  mailboxId: types.string(),
  threadId: types.string(),
  providerMessageId: types.string(),
  subject: types.string(),
  from: z.lazy(() => GetV1MessagesByMessageIdFrom$inboundSchema),
  snippet: types.string(),
  receivedAt: types.date(),
  labelIds: z.array(types.string()),
});

export function getV1MessagesByMessageIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1MessagesByMessageIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1MessagesByMessageIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1MessagesByMessageIdResponse' from JSON`,
  );
}
