/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetV1MessagesByMessageIdRequest = {
  messageId: string;
};

/** @internal */
export type GetV1MessagesByMessageIdRequest$Outbound = {
  messageId: string;
};

/** @internal */
export const GetV1MessagesByMessageIdRequest$outboundSchema: z.ZodMiniType<
  GetV1MessagesByMessageIdRequest$Outbound,
  GetV1MessagesByMessageIdRequest
> = z.object({
  messageId: z.string(),
});

export function getV1MessagesByMessageIdRequestToJSON(
  getV1MessagesByMessageIdRequest: GetV1MessagesByMessageIdRequest,
): string {
  return JSON.stringify(
    GetV1MessagesByMessageIdRequest$outboundSchema.parse(
      getV1MessagesByMessageIdRequest,
    ),
  );
}
