/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1ThreadsRequest = {
  cursor?: string | undefined;
  limit?: number | undefined;
  mailboxId: string;
};

export const GetV1ThreadsObject = {
  List: "list",
} as const;
export type GetV1ThreadsObject = ClosedEnum<typeof GetV1ThreadsObject>;

export const GetV1ThreadsObjectThread = {
  Thread: "thread",
} as const;
export type GetV1ThreadsObjectThread = ClosedEnum<
  typeof GetV1ThreadsObjectThread
>;

export type GetV1ThreadsData = {
  id: string;
  object: GetV1ThreadsObjectThread;
  mailboxId: string;
  providerThreadId: string;
  subject: string;
  lastMessageAt: Date;
};

/**
 * Mailbox threads
 */
export type GetV1ThreadsResponse = {
  object: GetV1ThreadsObject;
  data: Array<GetV1ThreadsData>;
  nextCursor: string | null;
};

/** @internal */
export type GetV1ThreadsRequest$Outbound = {
  cursor?: string | undefined;
  limit?: number | undefined;
  mailboxId: string;
};

/** @internal */
export const GetV1ThreadsRequest$outboundSchema: z.ZodMiniType<
  GetV1ThreadsRequest$Outbound,
  GetV1ThreadsRequest
> = z.object({
  cursor: z.optional(z.string()),
  limit: z.optional(z.int()),
  mailboxId: z.string(),
});

export function getV1ThreadsRequestToJSON(
  getV1ThreadsRequest: GetV1ThreadsRequest,
): string {
  return JSON.stringify(
    GetV1ThreadsRequest$outboundSchema.parse(getV1ThreadsRequest),
  );
}

/** @internal */
export const GetV1ThreadsObject$inboundSchema: z.ZodMiniEnum<
  typeof GetV1ThreadsObject
> = z.enum(GetV1ThreadsObject);

/** @internal */
export const GetV1ThreadsObjectThread$inboundSchema: z.ZodMiniEnum<
  typeof GetV1ThreadsObjectThread
> = z.enum(GetV1ThreadsObjectThread);

/** @internal */
export const GetV1ThreadsData$inboundSchema: z.ZodMiniType<
  GetV1ThreadsData,
  unknown
> = z.object({
  id: types.string(),
  object: GetV1ThreadsObjectThread$inboundSchema,
  mailboxId: types.string(),
  providerThreadId: types.string(),
  subject: types.string(),
  lastMessageAt: types.date(),
});

export function getV1ThreadsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ThreadsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ThreadsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ThreadsData' from JSON`,
  );
}

/** @internal */
export const GetV1ThreadsResponse$inboundSchema: z.ZodMiniType<
  GetV1ThreadsResponse,
  unknown
> = z.object({
  object: GetV1ThreadsObject$inboundSchema,
  data: z.array(z.lazy(() => GetV1ThreadsData$inboundSchema)),
  nextCursor: types.nullable(types.string()),
});

export function getV1ThreadsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ThreadsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ThreadsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ThreadsResponse' from JSON`,
  );
}
