/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetV1ReplaysByReplayIdRequest = {
  replayId: string;
};

/** @internal */
export type GetV1ReplaysByReplayIdRequest$Outbound = {
  replayId: string;
};

/** @internal */
export const GetV1ReplaysByReplayIdRequest$outboundSchema: z.ZodMiniType<
  GetV1ReplaysByReplayIdRequest$Outbound,
  GetV1ReplaysByReplayIdRequest
> = z.object({
  replayId: z.string(),
});

export function getV1ReplaysByReplayIdRequestToJSON(
  getV1ReplaysByReplayIdRequest: GetV1ReplaysByReplayIdRequest,
): string {
  return JSON.stringify(
    GetV1ReplaysByReplayIdRequest$outboundSchema.parse(
      getV1ReplaysByReplayIdRequest,
    ),
  );
}
