/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1ThreadsByThreadIdRequest = {
  threadId: string;
};

export const GetV1ThreadsByThreadIdObject = {
  Thread: "thread",
} as const;
export type GetV1ThreadsByThreadIdObject = ClosedEnum<
  typeof GetV1ThreadsByThreadIdObject
>;

export type Message = {
  id: string;
  subject: string;
  receivedAt: Date;
};

/**
 * Thread
 */
export type GetV1ThreadsByThreadIdResponse = {
  id: string;
  object: GetV1ThreadsByThreadIdObject;
  mailboxId: string;
  providerThreadId: string;
  subject: string;
  lastMessageAt: Date;
  messages: Array<Message>;
};

/** @internal */
export type GetV1ThreadsByThreadIdRequest$Outbound = {
  threadId: string;
};

/** @internal */
export const GetV1ThreadsByThreadIdRequest$outboundSchema: z.ZodMiniType<
  GetV1ThreadsByThreadIdRequest$Outbound,
  GetV1ThreadsByThreadIdRequest
> = z.object({
  threadId: z.string(),
});

export function getV1ThreadsByThreadIdRequestToJSON(
  getV1ThreadsByThreadIdRequest: GetV1ThreadsByThreadIdRequest,
): string {
  return JSON.stringify(
    GetV1ThreadsByThreadIdRequest$outboundSchema.parse(
      getV1ThreadsByThreadIdRequest,
    ),
  );
}

/** @internal */
export const GetV1ThreadsByThreadIdObject$inboundSchema: z.ZodMiniEnum<
  typeof GetV1ThreadsByThreadIdObject
> = z.enum(GetV1ThreadsByThreadIdObject);

/** @internal */
export const Message$inboundSchema: z.ZodMiniType<Message, unknown> = z.object({
  id: types.string(),
  subject: types.string(),
  receivedAt: types.date(),
});

export function messageFromJSON(
  jsonString: string,
): SafeParseResult<Message, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Message$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Message' from JSON`,
  );
}

/** @internal */
export const GetV1ThreadsByThreadIdResponse$inboundSchema: z.ZodMiniType<
  GetV1ThreadsByThreadIdResponse,
  unknown
> = z.object({
  id: types.string(),
  object: GetV1ThreadsByThreadIdObject$inboundSchema,
  mailboxId: types.string(),
  providerThreadId: types.string(),
  subject: types.string(),
  lastMessageAt: types.date(),
  messages: z.array(z.lazy(() => Message$inboundSchema)),
});

export function getV1ThreadsByThreadIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ThreadsByThreadIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ThreadsByThreadIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ThreadsByThreadIdResponse' from JSON`,
  );
}
