/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1MailboxesByMailboxIdObservabilityRequest = {
  mailboxId: string;
};

export const GetV1MailboxesByMailboxIdObservabilityObject = {
  MailboxObservability: "mailbox_observability",
} as const;
export type GetV1MailboxesByMailboxIdObservabilityObject = ClosedEnum<
  typeof GetV1MailboxesByMailboxIdObservabilityObject
>;

export const LagStatus = {
  Active: "active",
  ReconnectRequired: "reconnect_required",
  Disabled: "disabled",
} as const;
export type LagStatus = OpenEnum<typeof LagStatus>;

export const GetV1MailboxesByMailboxIdObservabilitySyncState = {
  Initializing: "initializing",
  Healthy: "healthy",
  Lagging: "lagging",
  Failed: "failed",
} as const;
export type GetV1MailboxesByMailboxIdObservabilitySyncState = OpenEnum<
  typeof GetV1MailboxesByMailboxIdObservabilitySyncState
>;

export const GetV1MailboxesByMailboxIdObservabilityWatchState = {
  Active: "active",
  Expiring: "expiring",
  Expired: "expired",
  Unhealthy: "unhealthy",
} as const;
export type GetV1MailboxesByMailboxIdObservabilityWatchState = OpenEnum<
  typeof GetV1MailboxesByMailboxIdObservabilityWatchState
>;

export type Lag = {
  status: LagStatus;
  syncState: GetV1MailboxesByMailboxIdObservabilitySyncState;
  watchState: GetV1MailboxesByMailboxIdObservabilityWatchState;
  lastSuccessfulSyncAt: Date | null;
  lagSeconds: number | null;
};

export type Cursor = {
  currentCursor: string | null;
  previousCursor: string | null;
  nextCursor: string | null;
  advanced: boolean | null;
  advancedAt: Date | null;
};

export type Lease = {
  activeLeaseOwner: string | null;
  activeLeaseHeartbeatAt: Date | null;
  activeLeaseExpiresAt: Date | null;
  contentionCount24h: number;
  latestContentionAt: Date | null;
  leaseLossCount24h: number;
  latestLeaseLossAt: Date | null;
};

export const GetV1MailboxesByMailboxIdObservabilityDeliveryState = {
  Healthy: "healthy",
  Degraded: "degraded",
  Failing: "failing",
} as const;
export type GetV1MailboxesByMailboxIdObservabilityDeliveryState = OpenEnum<
  typeof GetV1MailboxesByMailboxIdObservabilityDeliveryState
>;

export type GetV1MailboxesByMailboxIdObservabilityLastDeliveryError = {
  code: string;
  message: string;
  occurredAt: Date;
  retryable: boolean;
};

export type WebhookDelivery = {
  webhookEndpointId: string;
  webhookEndpointUrl: string;
  deliveryState: GetV1MailboxesByMailboxIdObservabilityDeliveryState;
  consecutiveFailures: number;
  pendingDeliveries: number;
  processingDeliveries: number;
  failedDeliveries: number;
  lastDeliveryAt: Date | null;
  lastDeliveryError:
    | GetV1MailboxesByMailboxIdObservabilityLastDeliveryError
    | null;
};

export const LatestSyncRunStatus = {
  Running: "running",
  Completed: "completed",
  SkippedDueToActiveLease: "skipped_due_to_active_lease",
  ReconnectRequired: "reconnect_required",
  DispatchRetryExhausted: "dispatch_retry_exhausted",
  FailedAfterLeaseAcquired: "failed_after_lease_acquired",
  LeaseLost: "lease_lost",
} as const;
export type LatestSyncRunStatus = OpenEnum<typeof LatestSyncRunStatus>;

export type LatestSyncRun = {
  syncRunId: string;
  mailboxId: string;
  startedAt: Date;
  completedAt: Date | null;
  status: LatestSyncRunStatus;
  detail: string | null;
  eventsEmitted: number | null;
  leaseOwnerId: string | null;
  previousCursor: string | null;
  nextCursor: string | null;
  cursorAdvanced: boolean | null;
};

/**
 * Mailbox observability
 */
export type GetV1MailboxesByMailboxIdObservabilityResponse = {
  object: GetV1MailboxesByMailboxIdObservabilityObject;
  mailboxId: string;
  generatedAt: Date;
  lag: Lag;
  cursor: Cursor;
  lease: Lease;
  webhookDeliveries: Array<WebhookDelivery>;
  latestSyncRun: LatestSyncRun | null;
};

/** @internal */
export type GetV1MailboxesByMailboxIdObservabilityRequest$Outbound = {
  mailboxId: string;
};

/** @internal */
export const GetV1MailboxesByMailboxIdObservabilityRequest$outboundSchema:
  z.ZodMiniType<
    GetV1MailboxesByMailboxIdObservabilityRequest$Outbound,
    GetV1MailboxesByMailboxIdObservabilityRequest
  > = z.object({
    mailboxId: z.string(),
  });

export function getV1MailboxesByMailboxIdObservabilityRequestToJSON(
  getV1MailboxesByMailboxIdObservabilityRequest:
    GetV1MailboxesByMailboxIdObservabilityRequest,
): string {
  return JSON.stringify(
    GetV1MailboxesByMailboxIdObservabilityRequest$outboundSchema.parse(
      getV1MailboxesByMailboxIdObservabilityRequest,
    ),
  );
}

/** @internal */
export const GetV1MailboxesByMailboxIdObservabilityObject$inboundSchema:
  z.ZodMiniEnum<typeof GetV1MailboxesByMailboxIdObservabilityObject> = z.enum(
    GetV1MailboxesByMailboxIdObservabilityObject,
  );

/** @internal */
export const LagStatus$inboundSchema: z.ZodMiniType<LagStatus, unknown> =
  openEnums.inboundSchema(LagStatus);

/** @internal */
export const GetV1MailboxesByMailboxIdObservabilitySyncState$inboundSchema:
  z.ZodMiniType<GetV1MailboxesByMailboxIdObservabilitySyncState, unknown> =
    openEnums.inboundSchema(GetV1MailboxesByMailboxIdObservabilitySyncState);

/** @internal */
export const GetV1MailboxesByMailboxIdObservabilityWatchState$inboundSchema:
  z.ZodMiniType<GetV1MailboxesByMailboxIdObservabilityWatchState, unknown> =
    openEnums.inboundSchema(GetV1MailboxesByMailboxIdObservabilityWatchState);

/** @internal */
export const Lag$inboundSchema: z.ZodMiniType<Lag, unknown> = z.object({
  status: LagStatus$inboundSchema,
  syncState: GetV1MailboxesByMailboxIdObservabilitySyncState$inboundSchema,
  watchState: GetV1MailboxesByMailboxIdObservabilityWatchState$inboundSchema,
  lastSuccessfulSyncAt: types.nullable(types.date()),
  lagSeconds: types.nullable(types.number()),
});

export function lagFromJSON(
  jsonString: string,
): SafeParseResult<Lag, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Lag$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Lag' from JSON`,
  );
}

/** @internal */
export const Cursor$inboundSchema: z.ZodMiniType<Cursor, unknown> = z.object({
  currentCursor: types.nullable(types.string()),
  previousCursor: types.nullable(types.string()),
  nextCursor: types.nullable(types.string()),
  advanced: types.nullable(types.boolean()),
  advancedAt: types.nullable(types.date()),
});

export function cursorFromJSON(
  jsonString: string,
): SafeParseResult<Cursor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Cursor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Cursor' from JSON`,
  );
}

/** @internal */
export const Lease$inboundSchema: z.ZodMiniType<Lease, unknown> = z.object({
  activeLeaseOwner: types.nullable(types.string()),
  activeLeaseHeartbeatAt: types.nullable(types.date()),
  activeLeaseExpiresAt: types.nullable(types.date()),
  contentionCount24h: types.number(),
  latestContentionAt: types.nullable(types.date()),
  leaseLossCount24h: types.number(),
  latestLeaseLossAt: types.nullable(types.date()),
});

export function leaseFromJSON(
  jsonString: string,
): SafeParseResult<Lease, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Lease$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Lease' from JSON`,
  );
}

/** @internal */
export const GetV1MailboxesByMailboxIdObservabilityDeliveryState$inboundSchema:
  z.ZodMiniType<GetV1MailboxesByMailboxIdObservabilityDeliveryState, unknown> =
    openEnums.inboundSchema(
      GetV1MailboxesByMailboxIdObservabilityDeliveryState,
    );

/** @internal */
export const GetV1MailboxesByMailboxIdObservabilityLastDeliveryError$inboundSchema:
  z.ZodMiniType<
    GetV1MailboxesByMailboxIdObservabilityLastDeliveryError,
    unknown
  > = z.object({
    code: types.string(),
    message: types.string(),
    occurredAt: types.date(),
    retryable: types.boolean(),
  });

export function getV1MailboxesByMailboxIdObservabilityLastDeliveryErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1MailboxesByMailboxIdObservabilityLastDeliveryError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1MailboxesByMailboxIdObservabilityLastDeliveryError$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetV1MailboxesByMailboxIdObservabilityLastDeliveryError' from JSON`,
  );
}

/** @internal */
export const WebhookDelivery$inboundSchema: z.ZodMiniType<
  WebhookDelivery,
  unknown
> = z.object({
  webhookEndpointId: types.string(),
  webhookEndpointUrl: types.string(),
  deliveryState:
    GetV1MailboxesByMailboxIdObservabilityDeliveryState$inboundSchema,
  consecutiveFailures: types.number(),
  pendingDeliveries: types.number(),
  processingDeliveries: types.number(),
  failedDeliveries: types.number(),
  lastDeliveryAt: types.nullable(types.date()),
  lastDeliveryError: types.nullable(
    z.lazy(() =>
      GetV1MailboxesByMailboxIdObservabilityLastDeliveryError$inboundSchema
    ),
  ),
});

export function webhookDeliveryFromJSON(
  jsonString: string,
): SafeParseResult<WebhookDelivery, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookDelivery$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookDelivery' from JSON`,
  );
}

/** @internal */
export const LatestSyncRunStatus$inboundSchema: z.ZodMiniType<
  LatestSyncRunStatus,
  unknown
> = openEnums.inboundSchema(LatestSyncRunStatus);

/** @internal */
export const LatestSyncRun$inboundSchema: z.ZodMiniType<
  LatestSyncRun,
  unknown
> = z.object({
  syncRunId: types.string(),
  mailboxId: types.string(),
  startedAt: types.date(),
  completedAt: types.nullable(types.date()),
  status: LatestSyncRunStatus$inboundSchema,
  detail: types.nullable(types.string()),
  eventsEmitted: types.nullable(types.number()),
  leaseOwnerId: types.nullable(types.string()),
  previousCursor: types.nullable(types.string()),
  nextCursor: types.nullable(types.string()),
  cursorAdvanced: types.nullable(types.boolean()),
});

export function latestSyncRunFromJSON(
  jsonString: string,
): SafeParseResult<LatestSyncRun, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LatestSyncRun$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LatestSyncRun' from JSON`,
  );
}

/** @internal */
export const GetV1MailboxesByMailboxIdObservabilityResponse$inboundSchema:
  z.ZodMiniType<GetV1MailboxesByMailboxIdObservabilityResponse, unknown> = z
    .object({
      object: GetV1MailboxesByMailboxIdObservabilityObject$inboundSchema,
      mailboxId: types.string(),
      generatedAt: types.date(),
      lag: z.lazy(() => Lag$inboundSchema),
      cursor: z.lazy(() => Cursor$inboundSchema),
      lease: z.lazy(() => Lease$inboundSchema),
      webhookDeliveries: z.array(z.lazy(() => WebhookDelivery$inboundSchema)),
      latestSyncRun: types.nullable(z.lazy(() => LatestSyncRun$inboundSchema)),
    });

export function getV1MailboxesByMailboxIdObservabilityResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1MailboxesByMailboxIdObservabilityResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1MailboxesByMailboxIdObservabilityResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1MailboxesByMailboxIdObservabilityResponse' from JSON`,
  );
}
