/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetV1MailboxesByMailboxIdObservabilityRequest = {
  mailboxId: string;
};

export const GetV1MailboxesByMailboxIdObservabilityObject = {
  MailboxObservability: "mailbox_observability",
} as const;
export type GetV1MailboxesByMailboxIdObservabilityObject = ClosedEnum<
  typeof GetV1MailboxesByMailboxIdObservabilityObject
>;

export type Lag = {
  status: models.MailboxStatus;
  syncState: models.SyncState;
  watchState: models.WatchState;
  lastSuccessfulSyncAt: Date | null;
  lagSeconds: number | null;
};

export type Cursor = {
  currentCursor: string | null;
  previousCursor: string | null;
  nextCursor: string | null;
  advanced: boolean | null;
  advancedAt: Date | null;
};

export type Lease = {
  activeLeaseOwner: string | null;
  activeLeaseHeartbeatAt: Date | null;
  activeLeaseExpiresAt: Date | null;
  contentionCount24h: number;
  latestContentionAt: Date | null;
  leaseLossCount24h: number;
  latestLeaseLossAt: Date | null;
};

export type WebhookDelivery = {
  webhookEndpointId: string;
  webhookEndpointUrl: string;
  deliveryState: models.DeliveryState;
  consecutiveFailures: number;
  pendingDeliveries: number;
  processingDeliveries: number;
  failedDeliveries: number;
  lastDeliveryAt: Date | null;
  lastDeliveryError: models.ErrorDetail | null;
};

/**
 * Mailbox observability
 */
export type GetV1MailboxesByMailboxIdObservabilityResponse = {
  object: GetV1MailboxesByMailboxIdObservabilityObject;
  mailboxId: string;
  generatedAt: Date;
  lag: Lag;
  cursor: Cursor;
  lease: Lease;
  webhookDeliveries: Array<WebhookDelivery>;
  latestSyncRun: models.SyncRun | null;
};

/** @internal */
export type GetV1MailboxesByMailboxIdObservabilityRequest$Outbound = {
  mailboxId: string;
};

/** @internal */
export const GetV1MailboxesByMailboxIdObservabilityRequest$outboundSchema:
  z.ZodMiniType<
    GetV1MailboxesByMailboxIdObservabilityRequest$Outbound,
    GetV1MailboxesByMailboxIdObservabilityRequest
  > = z.object({
    mailboxId: z.string(),
  });

export function getV1MailboxesByMailboxIdObservabilityRequestToJSON(
  getV1MailboxesByMailboxIdObservabilityRequest:
    GetV1MailboxesByMailboxIdObservabilityRequest,
): string {
  return JSON.stringify(
    GetV1MailboxesByMailboxIdObservabilityRequest$outboundSchema.parse(
      getV1MailboxesByMailboxIdObservabilityRequest,
    ),
  );
}

/** @internal */
export const GetV1MailboxesByMailboxIdObservabilityObject$inboundSchema:
  z.ZodMiniEnum<typeof GetV1MailboxesByMailboxIdObservabilityObject> = z.enum(
    GetV1MailboxesByMailboxIdObservabilityObject,
  );

/** @internal */
export const Lag$inboundSchema: z.ZodMiniType<Lag, unknown> = z.object({
  status: models.MailboxStatus$inboundSchema,
  syncState: models.SyncState$inboundSchema,
  watchState: models.WatchState$inboundSchema,
  lastSuccessfulSyncAt: types.nullable(types.date()),
  lagSeconds: types.nullable(types.number()),
});

export function lagFromJSON(
  jsonString: string,
): SafeParseResult<Lag, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Lag$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Lag' from JSON`,
  );
}

/** @internal */
export const Cursor$inboundSchema: z.ZodMiniType<Cursor, unknown> = z.object({
  currentCursor: types.nullable(types.string()),
  previousCursor: types.nullable(types.string()),
  nextCursor: types.nullable(types.string()),
  advanced: types.nullable(types.boolean()),
  advancedAt: types.nullable(types.date()),
});

export function cursorFromJSON(
  jsonString: string,
): SafeParseResult<Cursor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Cursor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Cursor' from JSON`,
  );
}

/** @internal */
export const Lease$inboundSchema: z.ZodMiniType<Lease, unknown> = z.object({
  activeLeaseOwner: types.nullable(types.string()),
  activeLeaseHeartbeatAt: types.nullable(types.date()),
  activeLeaseExpiresAt: types.nullable(types.date()),
  contentionCount24h: types.number(),
  latestContentionAt: types.nullable(types.date()),
  leaseLossCount24h: types.number(),
  latestLeaseLossAt: types.nullable(types.date()),
});

export function leaseFromJSON(
  jsonString: string,
): SafeParseResult<Lease, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Lease$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Lease' from JSON`,
  );
}

/** @internal */
export const WebhookDelivery$inboundSchema: z.ZodMiniType<
  WebhookDelivery,
  unknown
> = z.object({
  webhookEndpointId: types.string(),
  webhookEndpointUrl: types.string(),
  deliveryState: models.DeliveryState$inboundSchema,
  consecutiveFailures: types.number(),
  pendingDeliveries: types.number(),
  processingDeliveries: types.number(),
  failedDeliveries: types.number(),
  lastDeliveryAt: types.nullable(types.date()),
  lastDeliveryError: types.nullable(models.ErrorDetail$inboundSchema),
});

export function webhookDeliveryFromJSON(
  jsonString: string,
): SafeParseResult<WebhookDelivery, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookDelivery$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookDelivery' from JSON`,
  );
}

/** @internal */
export const GetV1MailboxesByMailboxIdObservabilityResponse$inboundSchema:
  z.ZodMiniType<GetV1MailboxesByMailboxIdObservabilityResponse, unknown> = z
    .object({
      object: GetV1MailboxesByMailboxIdObservabilityObject$inboundSchema,
      mailboxId: types.string(),
      generatedAt: types.date(),
      lag: z.lazy(() => Lag$inboundSchema),
      cursor: z.lazy(() => Cursor$inboundSchema),
      lease: z.lazy(() => Lease$inboundSchema),
      webhookDeliveries: z.array(z.lazy(() => WebhookDelivery$inboundSchema)),
      latestSyncRun: types.nullable(models.SyncRun$inboundSchema),
    });

export function getV1MailboxesByMailboxIdObservabilityResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1MailboxesByMailboxIdObservabilityResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1MailboxesByMailboxIdObservabilityResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1MailboxesByMailboxIdObservabilityResponse' from JSON`,
  );
}
