/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type MailboxesGetObservabilityRequest = {
  mailboxId: string;
};

/** @internal */
export type MailboxesGetObservabilityRequest$Outbound = {
  mailboxId: string;
};

/** @internal */
export const MailboxesGetObservabilityRequest$outboundSchema: z.ZodMiniType<
  MailboxesGetObservabilityRequest$Outbound,
  MailboxesGetObservabilityRequest
> = z.object({
  mailboxId: z.string(),
});

export function mailboxesGetObservabilityRequestToJSON(
  mailboxesGetObservabilityRequest: MailboxesGetObservabilityRequest,
): string {
  return JSON.stringify(
    MailboxesGetObservabilityRequest$outboundSchema.parse(
      mailboxesGetObservabilityRequest,
    ),
  );
}
