/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type MailboxesListSyncRunsRequest = {
  cursor?: string | undefined;
  limit?: number | undefined;
  mailboxId: string;
};

export type MailboxesListSyncRunsResponse = {
  result: models.SyncRunList;
};

/** @internal */
export type MailboxesListSyncRunsRequest$Outbound = {
  cursor?: string | undefined;
  limit?: number | undefined;
  mailboxId: string;
};

/** @internal */
export const MailboxesListSyncRunsRequest$outboundSchema: z.ZodMiniType<
  MailboxesListSyncRunsRequest$Outbound,
  MailboxesListSyncRunsRequest
> = z.object({
  cursor: z.optional(z.string()),
  limit: z.optional(z.int()),
  mailboxId: z.string(),
});

export function mailboxesListSyncRunsRequestToJSON(
  mailboxesListSyncRunsRequest: MailboxesListSyncRunsRequest,
): string {
  return JSON.stringify(
    MailboxesListSyncRunsRequest$outboundSchema.parse(
      mailboxesListSyncRunsRequest,
    ),
  );
}

/** @internal */
export const MailboxesListSyncRunsResponse$inboundSchema: z.ZodMiniType<
  MailboxesListSyncRunsResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.SyncRunList$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function mailboxesListSyncRunsResponseFromJSON(
  jsonString: string,
): SafeParseResult<MailboxesListSyncRunsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MailboxesListSyncRunsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MailboxesListSyncRunsResponse' from JSON`,
  );
}
