/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type MessagesListRequest = {
  cursor?: string | undefined;
  limit?: number | undefined;
  mailboxId: string;
};

export type MessagesListResponse = {
  result: models.MessageList;
};

/** @internal */
export type MessagesListRequest$Outbound = {
  cursor?: string | undefined;
  limit?: number | undefined;
  mailboxId: string;
};

/** @internal */
export const MessagesListRequest$outboundSchema: z.ZodMiniType<
  MessagesListRequest$Outbound,
  MessagesListRequest
> = z.object({
  cursor: z.optional(z.string()),
  limit: z.optional(z.int()),
  mailboxId: z.string(),
});

export function messagesListRequestToJSON(
  messagesListRequest: MessagesListRequest,
): string {
  return JSON.stringify(
    MessagesListRequest$outboundSchema.parse(messagesListRequest),
  );
}

/** @internal */
export const MessagesListResponse$inboundSchema: z.ZodMiniType<
  MessagesListResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.MessageList$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function messagesListResponseFromJSON(
  jsonString: string,
): SafeParseResult<MessagesListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MessagesListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MessagesListResponse' from JSON`,
  );
}
