/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1a8f4d348142
 */

import * as z from "zod/v4-mini";

export type MessagesGetRequest = {
  messageId: string;
};

/** @internal */
export type MessagesGetRequest$Outbound = {
  messageId: string;
};

/** @internal */
export const MessagesGetRequest$outboundSchema: z.ZodMiniType<
  MessagesGetRequest$Outbound,
  MessagesGetRequest
> = z.object({
  messageId: z.string(),
});

export function messagesGetRequestToJSON(
  messagesGetRequest: MessagesGetRequest,
): string {
  return JSON.stringify(
    MessagesGetRequest$outboundSchema.parse(messagesGetRequest),
  );
}
