/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PostV1WebhookEndpointsRequest = {
  url: string;
  description?: string | null | undefined;
};

export const PostV1WebhookEndpointsObject = {
  WebhookEndpoint: "webhook_endpoint",
} as const;
export type PostV1WebhookEndpointsObject = ClosedEnum<
  typeof PostV1WebhookEndpointsObject
>;

export const PostV1WebhookEndpointsDeliveryState = {
  Healthy: "healthy",
  Degraded: "degraded",
  Failing: "failing",
} as const;
export type PostV1WebhookEndpointsDeliveryState = OpenEnum<
  typeof PostV1WebhookEndpointsDeliveryState
>;

export type PostV1WebhookEndpointsLastDeliveryError = {
  code: string;
  message: string;
  occurredAt: Date;
  retryable: boolean;
};

/**
 * Webhook endpoint created
 */
export type PostV1WebhookEndpointsResponse = {
  id: string;
  object: PostV1WebhookEndpointsObject;
  url: string;
  description: string | null;
  deliveryState: PostV1WebhookEndpointsDeliveryState;
  lastDeliveryAt: Date | null;
  lastDeliveryError: PostV1WebhookEndpointsLastDeliveryError | null;
  createdAt: Date;
  secret: string;
};

/** @internal */
export type PostV1WebhookEndpointsRequest$Outbound = {
  url: string;
  description?: string | null | undefined;
};

/** @internal */
export const PostV1WebhookEndpointsRequest$outboundSchema: z.ZodMiniType<
  PostV1WebhookEndpointsRequest$Outbound,
  PostV1WebhookEndpointsRequest
> = z.object({
  url: z.string(),
  description: z.optional(z.nullable(z.string())),
});

export function postV1WebhookEndpointsRequestToJSON(
  postV1WebhookEndpointsRequest: PostV1WebhookEndpointsRequest,
): string {
  return JSON.stringify(
    PostV1WebhookEndpointsRequest$outboundSchema.parse(
      postV1WebhookEndpointsRequest,
    ),
  );
}

/** @internal */
export const PostV1WebhookEndpointsObject$inboundSchema: z.ZodMiniEnum<
  typeof PostV1WebhookEndpointsObject
> = z.enum(PostV1WebhookEndpointsObject);

/** @internal */
export const PostV1WebhookEndpointsDeliveryState$inboundSchema: z.ZodMiniType<
  PostV1WebhookEndpointsDeliveryState,
  unknown
> = openEnums.inboundSchema(PostV1WebhookEndpointsDeliveryState);

/** @internal */
export const PostV1WebhookEndpointsLastDeliveryError$inboundSchema:
  z.ZodMiniType<PostV1WebhookEndpointsLastDeliveryError, unknown> = z.object({
    code: types.string(),
    message: types.string(),
    occurredAt: types.date(),
    retryable: types.boolean(),
  });

export function postV1WebhookEndpointsLastDeliveryErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  PostV1WebhookEndpointsLastDeliveryError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1WebhookEndpointsLastDeliveryError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostV1WebhookEndpointsLastDeliveryError' from JSON`,
  );
}

/** @internal */
export const PostV1WebhookEndpointsResponse$inboundSchema: z.ZodMiniType<
  PostV1WebhookEndpointsResponse,
  unknown
> = z.object({
  id: types.string(),
  object: PostV1WebhookEndpointsObject$inboundSchema,
  url: types.string(),
  description: types.nullable(types.string()),
  deliveryState: PostV1WebhookEndpointsDeliveryState$inboundSchema,
  lastDeliveryAt: types.nullable(types.date()),
  lastDeliveryError: types.nullable(
    z.lazy(() => PostV1WebhookEndpointsLastDeliveryError$inboundSchema),
  ),
  createdAt: types.date(),
  secret: types.string(),
});

export function postV1WebhookEndpointsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1WebhookEndpointsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1WebhookEndpointsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1WebhookEndpointsResponse' from JSON`,
  );
}
