/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type PostV1ReplaysRequest = {
  mailboxId: string;
  webhookEndpointId: string;
  startTime: string;
  endTime: string;
};

/** @internal */
export type PostV1ReplaysRequest$Outbound = {
  mailboxId: string;
  webhookEndpointId: string;
  startTime: string;
  endTime: string;
};

/** @internal */
export const PostV1ReplaysRequest$outboundSchema: z.ZodMiniType<
  PostV1ReplaysRequest$Outbound,
  PostV1ReplaysRequest
> = z.object({
  mailboxId: z.string(),
  webhookEndpointId: z.string(),
  startTime: z.string(),
  endTime: z.string(),
});

export function postV1ReplaysRequestToJSON(
  postV1ReplaysRequest: PostV1ReplaysRequest,
): string {
  return JSON.stringify(
    PostV1ReplaysRequest$outboundSchema.parse(postV1ReplaysRequest),
  );
}
