/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type MailboxId = string;

export const EventTypeRequestEnum2 = {
  MessageCreated: "message.created",
  MessageUpdated: "message.updated",
  ThreadUpdated: "thread.updated",
} as const;
export type EventTypeRequestEnum2 = ClosedEnum<typeof EventTypeRequestEnum2>;

export type EventType = EventTypeRequestEnum2;

export type PostV1WebhookEndpointsByEndpointIdSubscriptionsRequestBody = {
  mailboxIds: Array<string>;
  eventTypes: Array<EventTypeRequestEnum2>;
};

export type PostV1WebhookEndpointsByEndpointIdSubscriptionsRequest = {
  endpointId: string;
  body: PostV1WebhookEndpointsByEndpointIdSubscriptionsRequestBody;
};

export const PostV1WebhookEndpointsByEndpointIdSubscriptionsObject = {
  List: "list",
} as const;
export type PostV1WebhookEndpointsByEndpointIdSubscriptionsObject = ClosedEnum<
  typeof PostV1WebhookEndpointsByEndpointIdSubscriptionsObject
>;

export const ObjectWebhookEndpointSubscription = {
  WebhookEndpointSubscription: "webhook_endpoint_subscription",
} as const;
export type ObjectWebhookEndpointSubscription = ClosedEnum<
  typeof ObjectWebhookEndpointSubscription
>;

export const EventTypeResponse = {
  MessageCreated: "message.created",
  MessageUpdated: "message.updated",
  ThreadUpdated: "thread.updated",
} as const;
export type EventTypeResponse = OpenEnum<typeof EventTypeResponse>;

export type PostV1WebhookEndpointsByEndpointIdSubscriptionsData = {
  id: string;
  object: ObjectWebhookEndpointSubscription;
  webhookEndpointId: string;
  mailboxId: string;
  eventTypes: Array<EventTypeResponse>;
  createdAt: Date;
};

/**
 * Webhook subscriptions created
 */
export type PostV1WebhookEndpointsByEndpointIdSubscriptionsResponse = {
  object: PostV1WebhookEndpointsByEndpointIdSubscriptionsObject;
  data: Array<PostV1WebhookEndpointsByEndpointIdSubscriptionsData>;
  nextCursor: string | null;
};

/** @internal */
export type MailboxId$Outbound = string;

/** @internal */
export const MailboxId$outboundSchema: z.ZodMiniType<
  MailboxId$Outbound,
  MailboxId
> = z.string();

export function mailboxIdToJSON(mailboxId: MailboxId): string {
  return JSON.stringify(MailboxId$outboundSchema.parse(mailboxId));
}

/** @internal */
export const EventTypeRequestEnum2$outboundSchema: z.ZodMiniEnum<
  typeof EventTypeRequestEnum2
> = z.enum(EventTypeRequestEnum2);

/** @internal */
export type EventType$Outbound = string;

/** @internal */
export const EventType$outboundSchema: z.ZodMiniType<
  EventType$Outbound,
  EventType
> = EventTypeRequestEnum2$outboundSchema;

export function eventTypeToJSON(eventType: EventType): string {
  return JSON.stringify(EventType$outboundSchema.parse(eventType));
}

/** @internal */
export type PostV1WebhookEndpointsByEndpointIdSubscriptionsRequestBody$Outbound =
  {
    mailboxIds: Array<string>;
    eventTypes: Array<string>;
  };

/** @internal */
export const PostV1WebhookEndpointsByEndpointIdSubscriptionsRequestBody$outboundSchema:
  z.ZodMiniType<
    PostV1WebhookEndpointsByEndpointIdSubscriptionsRequestBody$Outbound,
    PostV1WebhookEndpointsByEndpointIdSubscriptionsRequestBody
  > = z.object({
    mailboxIds: z.array(z.string()),
    eventTypes: z.array(EventTypeRequestEnum2$outboundSchema),
  });

export function postV1WebhookEndpointsByEndpointIdSubscriptionsRequestBodyToJSON(
  postV1WebhookEndpointsByEndpointIdSubscriptionsRequestBody:
    PostV1WebhookEndpointsByEndpointIdSubscriptionsRequestBody,
): string {
  return JSON.stringify(
    PostV1WebhookEndpointsByEndpointIdSubscriptionsRequestBody$outboundSchema
      .parse(postV1WebhookEndpointsByEndpointIdSubscriptionsRequestBody),
  );
}

/** @internal */
export type PostV1WebhookEndpointsByEndpointIdSubscriptionsRequest$Outbound = {
  endpointId: string;
  body: PostV1WebhookEndpointsByEndpointIdSubscriptionsRequestBody$Outbound;
};

/** @internal */
export const PostV1WebhookEndpointsByEndpointIdSubscriptionsRequest$outboundSchema:
  z.ZodMiniType<
    PostV1WebhookEndpointsByEndpointIdSubscriptionsRequest$Outbound,
    PostV1WebhookEndpointsByEndpointIdSubscriptionsRequest
  > = z.object({
    endpointId: z.string(),
    body: z.lazy(() =>
      PostV1WebhookEndpointsByEndpointIdSubscriptionsRequestBody$outboundSchema
    ),
  });

export function postV1WebhookEndpointsByEndpointIdSubscriptionsRequestToJSON(
  postV1WebhookEndpointsByEndpointIdSubscriptionsRequest:
    PostV1WebhookEndpointsByEndpointIdSubscriptionsRequest,
): string {
  return JSON.stringify(
    PostV1WebhookEndpointsByEndpointIdSubscriptionsRequest$outboundSchema.parse(
      postV1WebhookEndpointsByEndpointIdSubscriptionsRequest,
    ),
  );
}

/** @internal */
export const PostV1WebhookEndpointsByEndpointIdSubscriptionsObject$inboundSchema:
  z.ZodMiniEnum<typeof PostV1WebhookEndpointsByEndpointIdSubscriptionsObject> =
    z.enum(PostV1WebhookEndpointsByEndpointIdSubscriptionsObject);

/** @internal */
export const ObjectWebhookEndpointSubscription$inboundSchema: z.ZodMiniEnum<
  typeof ObjectWebhookEndpointSubscription
> = z.enum(ObjectWebhookEndpointSubscription);

/** @internal */
export const EventTypeResponse$inboundSchema: z.ZodMiniType<
  EventTypeResponse,
  unknown
> = openEnums.inboundSchema(EventTypeResponse);

/** @internal */
export const PostV1WebhookEndpointsByEndpointIdSubscriptionsData$inboundSchema:
  z.ZodMiniType<PostV1WebhookEndpointsByEndpointIdSubscriptionsData, unknown> =
    z.object({
      id: types.string(),
      object: ObjectWebhookEndpointSubscription$inboundSchema,
      webhookEndpointId: types.string(),
      mailboxId: types.string(),
      eventTypes: z.array(EventTypeResponse$inboundSchema),
      createdAt: types.date(),
    });

export function postV1WebhookEndpointsByEndpointIdSubscriptionsDataFromJSON(
  jsonString: string,
): SafeParseResult<
  PostV1WebhookEndpointsByEndpointIdSubscriptionsData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1WebhookEndpointsByEndpointIdSubscriptionsData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostV1WebhookEndpointsByEndpointIdSubscriptionsData' from JSON`,
  );
}

/** @internal */
export const PostV1WebhookEndpointsByEndpointIdSubscriptionsResponse$inboundSchema:
  z.ZodMiniType<
    PostV1WebhookEndpointsByEndpointIdSubscriptionsResponse,
    unknown
  > = z.object({
    object: PostV1WebhookEndpointsByEndpointIdSubscriptionsObject$inboundSchema,
    data: z.array(
      z.lazy(() =>
        PostV1WebhookEndpointsByEndpointIdSubscriptionsData$inboundSchema
      ),
    ),
    nextCursor: types.nullable(types.string()),
  });

export function postV1WebhookEndpointsByEndpointIdSubscriptionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PostV1WebhookEndpointsByEndpointIdSubscriptionsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1WebhookEndpointsByEndpointIdSubscriptionsResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PostV1WebhookEndpointsByEndpointIdSubscriptionsResponse' from JSON`,
  );
}
