/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const PostV1MailboxesConnectSessionsProviderEnum = {
  Gmail: "gmail",
} as const;
export type PostV1MailboxesConnectSessionsProviderEnum = ClosedEnum<
  typeof PostV1MailboxesConnectSessionsProviderEnum
>;

export type Provider = PostV1MailboxesConnectSessionsProviderEnum;

export type PostV1MailboxesConnectSessionsRequest = {
  provider: PostV1MailboxesConnectSessionsProviderEnum;
  tenantExternalId: string;
  mailboxExternalId: string;
  redirectUrl: string;
};

export const PostV1MailboxesConnectSessionsObject = {
  ConnectSession: "connect_session",
} as const;
export type PostV1MailboxesConnectSessionsObject = ClosedEnum<
  typeof PostV1MailboxesConnectSessionsObject
>;

/**
 * Connect session created
 */
export type PostV1MailboxesConnectSessionsResponse = {
  id: string;
  object: PostV1MailboxesConnectSessionsObject;
  connectUrl: string;
  expiresAt: Date;
};

/** @internal */
export const PostV1MailboxesConnectSessionsProviderEnum$outboundSchema:
  z.ZodMiniEnum<typeof PostV1MailboxesConnectSessionsProviderEnum> = z.enum(
    PostV1MailboxesConnectSessionsProviderEnum,
  );

/** @internal */
export type Provider$Outbound = string;

/** @internal */
export const Provider$outboundSchema: z.ZodMiniType<
  Provider$Outbound,
  Provider
> = PostV1MailboxesConnectSessionsProviderEnum$outboundSchema;

export function providerToJSON(provider: Provider): string {
  return JSON.stringify(Provider$outboundSchema.parse(provider));
}

/** @internal */
export type PostV1MailboxesConnectSessionsRequest$Outbound = {
  provider: string;
  tenantExternalId: string;
  mailboxExternalId: string;
  redirectUrl: string;
};

/** @internal */
export const PostV1MailboxesConnectSessionsRequest$outboundSchema:
  z.ZodMiniType<
    PostV1MailboxesConnectSessionsRequest$Outbound,
    PostV1MailboxesConnectSessionsRequest
  > = z.object({
    provider: PostV1MailboxesConnectSessionsProviderEnum$outboundSchema,
    tenantExternalId: z.string(),
    mailboxExternalId: z.string(),
    redirectUrl: z.string(),
  });

export function postV1MailboxesConnectSessionsRequestToJSON(
  postV1MailboxesConnectSessionsRequest: PostV1MailboxesConnectSessionsRequest,
): string {
  return JSON.stringify(
    PostV1MailboxesConnectSessionsRequest$outboundSchema.parse(
      postV1MailboxesConnectSessionsRequest,
    ),
  );
}

/** @internal */
export const PostV1MailboxesConnectSessionsObject$inboundSchema: z.ZodMiniEnum<
  typeof PostV1MailboxesConnectSessionsObject
> = z.enum(PostV1MailboxesConnectSessionsObject);

/** @internal */
export const PostV1MailboxesConnectSessionsResponse$inboundSchema:
  z.ZodMiniType<PostV1MailboxesConnectSessionsResponse, unknown> = z.object({
    id: types.string(),
    object: PostV1MailboxesConnectSessionsObject$inboundSchema,
    connectUrl: types.string(),
    expiresAt: types.date(),
  });

export function postV1MailboxesConnectSessionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1MailboxesConnectSessionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1MailboxesConnectSessionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1MailboxesConnectSessionsResponse' from JSON`,
  );
}
