/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type PostV1WebhookEndpointsRequest = {
  url: string;
  description?: string | null | undefined;
};

export const PostV1WebhookEndpointsObject = {
  WebhookEndpoint: "webhook_endpoint",
} as const;
export type PostV1WebhookEndpointsObject = ClosedEnum<
  typeof PostV1WebhookEndpointsObject
>;

export const DeliveryState = {
  Healthy: "healthy",
  Degraded: "degraded",
  Failing: "failing",
} as const;
export type DeliveryState = OpenEnum<typeof DeliveryState>;

/**
 * Webhook endpoint created
 */
export type PostV1WebhookEndpointsResponse = {
  id: string;
  object: PostV1WebhookEndpointsObject;
  url: string;
  description: string | null;
  deliveryState: DeliveryState;
  lastDeliveryAt: Date | null;
  lastDeliveryError: models.ErrorDetail | null;
  createdAt: Date;
  secret: string;
};

/** @internal */
export type PostV1WebhookEndpointsRequest$Outbound = {
  url: string;
  description?: string | null | undefined;
};

/** @internal */
export const PostV1WebhookEndpointsRequest$outboundSchema: z.ZodMiniType<
  PostV1WebhookEndpointsRequest$Outbound,
  PostV1WebhookEndpointsRequest
> = z.object({
  url: z.string(),
  description: z.optional(z.nullable(z.string())),
});

export function postV1WebhookEndpointsRequestToJSON(
  postV1WebhookEndpointsRequest: PostV1WebhookEndpointsRequest,
): string {
  return JSON.stringify(
    PostV1WebhookEndpointsRequest$outboundSchema.parse(
      postV1WebhookEndpointsRequest,
    ),
  );
}

/** @internal */
export const PostV1WebhookEndpointsObject$inboundSchema: z.ZodMiniEnum<
  typeof PostV1WebhookEndpointsObject
> = z.enum(PostV1WebhookEndpointsObject);

/** @internal */
export const DeliveryState$inboundSchema: z.ZodMiniType<
  DeliveryState,
  unknown
> = openEnums.inboundSchema(DeliveryState);

/** @internal */
export const PostV1WebhookEndpointsResponse$inboundSchema: z.ZodMiniType<
  PostV1WebhookEndpointsResponse,
  unknown
> = z.object({
  id: types.string(),
  object: PostV1WebhookEndpointsObject$inboundSchema,
  url: types.string(),
  description: types.nullable(types.string()),
  deliveryState: DeliveryState$inboundSchema,
  lastDeliveryAt: types.nullable(types.date()),
  lastDeliveryError: types.nullable(models.ErrorDetail$inboundSchema),
  createdAt: types.date(),
  secret: types.string(),
});

export function postV1WebhookEndpointsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1WebhookEndpointsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1WebhookEndpointsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1WebhookEndpointsResponse' from JSON`,
  );
}
