/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ReplaysGetRequest = {
  replayId: string;
};

/** @internal */
export type ReplaysGetRequest$Outbound = {
  replayId: string;
};

/** @internal */
export const ReplaysGetRequest$outboundSchema: z.ZodMiniType<
  ReplaysGetRequest$Outbound,
  ReplaysGetRequest
> = z.object({
  replayId: z.string(),
});

export function replaysGetRequestToJSON(
  replaysGetRequest: ReplaysGetRequest,
): string {
  return JSON.stringify(
    ReplaysGetRequest$outboundSchema.parse(replaysGetRequest),
  );
}
