/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ThreadsGetRequest = {
  threadId: string;
};

/** @internal */
export type ThreadsGetRequest$Outbound = {
  threadId: string;
};

/** @internal */
export const ThreadsGetRequest$outboundSchema: z.ZodMiniType<
  ThreadsGetRequest$Outbound,
  ThreadsGetRequest
> = z.object({
  threadId: z.string(),
});

export function threadsGetRequestToJSON(
  threadsGetRequest: ThreadsGetRequest,
): string {
  return JSON.stringify(
    ThreadsGetRequest$outboundSchema.parse(threadsGetRequest),
  );
}
