/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5def79ae7170
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type WebhookEndpointsCreateSubscriptionRequest = {
  endpointId: string;
  body: models.CreateWebhookEndpointSubscriptionRequest;
};

/** @internal */
export type WebhookEndpointsCreateSubscriptionRequest$Outbound = {
  endpointId: string;
  body: models.CreateWebhookEndpointSubscriptionRequest$Outbound;
};

/** @internal */
export const WebhookEndpointsCreateSubscriptionRequest$outboundSchema:
  z.ZodMiniType<
    WebhookEndpointsCreateSubscriptionRequest$Outbound,
    WebhookEndpointsCreateSubscriptionRequest
  > = z.object({
    endpointId: z.string(),
    body: models.CreateWebhookEndpointSubscriptionRequest$outboundSchema,
  });

export function webhookEndpointsCreateSubscriptionRequestToJSON(
  webhookEndpointsCreateSubscriptionRequest:
    WebhookEndpointsCreateSubscriptionRequest,
): string {
  return JSON.stringify(
    WebhookEndpointsCreateSubscriptionRequest$outboundSchema.parse(
      webhookEndpointsCreateSubscriptionRequest,
    ),
  );
}
