/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 87ca2f3717f8
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const MailboxStatus = {
  Active: "active",
  ReconnectRequired: "reconnect_required",
  Disabled: "disabled",
} as const;
export type MailboxStatus = OpenEnum<typeof MailboxStatus>;

/** @internal */
export const MailboxStatus$inboundSchema: z.ZodMiniType<
  MailboxStatus,
  unknown
> = openEnums.inboundSchema(MailboxStatus);
