/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f992545bfe68
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const WebhookEventType = {
  MessageCreated: "message.created",
  MessageUpdated: "message.updated",
  ThreadUpdated: "thread.updated",
} as const;
export type WebhookEventType = OpenEnum<typeof WebhookEventType>;

/** @internal */
export const WebhookEventType$inboundSchema: z.ZodMiniType<
  WebhookEventType,
  unknown
> = openEnums.inboundSchema(WebhookEventType);
/** @internal */
export const WebhookEventType$outboundSchema: z.ZodMiniType<
  string,
  WebhookEventType
> = openEnums.outboundSchema(WebhookEventType);
