// This file was auto-generated by Fern from our API Definition.
export var GetV1MailboxesByMailboxIdObservabilityResponse;
(function (GetV1MailboxesByMailboxIdObservabilityResponse) {
    GetV1MailboxesByMailboxIdObservabilityResponse.Object_ = {
        MailboxObservability: "mailbox_observability",
    };
    let Lag;
    (function (Lag) {
        Lag.Status = {
            Active: "active",
            ReconnectRequired: "reconnect_required",
            Disabled: "disabled",
        };
        Lag.SyncState = {
            Initializing: "initializing",
            Healthy: "healthy",
            Lagging: "lagging",
            Failed: "failed",
        };
        Lag.WatchState = {
            Active: "active",
            Expiring: "expiring",
            Expired: "expired",
            Unhealthy: "unhealthy",
        };
    })(Lag = GetV1MailboxesByMailboxIdObservabilityResponse.Lag || (GetV1MailboxesByMailboxIdObservabilityResponse.Lag = {}));
    let WebhookDeliveries;
    (function (WebhookDeliveries) {
        let Item;
        (function (Item) {
            Item.DeliveryState = {
                Healthy: "healthy",
                Degraded: "degraded",
                Failing: "failing",
            };
        })(Item = WebhookDeliveries.Item || (WebhookDeliveries.Item = {}));
    })(WebhookDeliveries = GetV1MailboxesByMailboxIdObservabilityResponse.WebhookDeliveries || (GetV1MailboxesByMailboxIdObservabilityResponse.WebhookDeliveries = {}));
    let LatestSyncRun;
    (function (LatestSyncRun) {
        LatestSyncRun.Status = {
            Running: "running",
            Completed: "completed",
            SkippedDueToActiveLease: "skipped_due_to_active_lease",
            ReconnectRequired: "reconnect_required",
            DispatchRetryExhausted: "dispatch_retry_exhausted",
            FailedAfterLeaseAcquired: "failed_after_lease_acquired",
            LeaseLost: "lease_lost",
        };
    })(LatestSyncRun = GetV1MailboxesByMailboxIdObservabilityResponse.LatestSyncRun || (GetV1MailboxesByMailboxIdObservabilityResponse.LatestSyncRun = {}));
})(GetV1MailboxesByMailboxIdObservabilityResponse || (GetV1MailboxesByMailboxIdObservabilityResponse = {}));
