// This file was auto-generated by Fern from our API Definition.
export var GetV1ReplaysByReplayIdResponse;
(function (GetV1ReplaysByReplayIdResponse) {
    GetV1ReplaysByReplayIdResponse.Object_ = {
        Replay: "replay",
    };
    GetV1ReplaysByReplayIdResponse.Status = {
        Queued: "queued",
        Running: "running",
        Completed: "completed",
        Failed: "failed",
        Cancelled: "cancelled",
    };
})(GetV1ReplaysByReplayIdResponse || (GetV1ReplaysByReplayIdResponse = {}));
