// This file was auto-generated by Fern from our API Definition.
export var GetV1ThreadsByThreadIdResponse;
(function (GetV1ThreadsByThreadIdResponse) {
    GetV1ThreadsByThreadIdResponse.Object_ = {
        Thread: "thread",
    };
})(GetV1ThreadsByThreadIdResponse || (GetV1ThreadsByThreadIdResponse = {}));
