// This file was auto-generated by Fern from our API Definition.
export var GetV1ThreadsResponse;
(function (GetV1ThreadsResponse) {
    GetV1ThreadsResponse.Object_ = {
        List: "list",
    };
    let Data;
    (function (Data) {
        let Item;
        (function (Item) {
            Item.Object_ = {
                Thread: "thread",
            };
        })(Item = Data.Item || (Data.Item = {}));
    })(Data = GetV1ThreadsResponse.Data || (GetV1ThreadsResponse.Data = {}));
})(GetV1ThreadsResponse || (GetV1ThreadsResponse = {}));
