// This file was auto-generated by Fern from our API Definition.
export var GetV1MailboxesByMailboxIdSyncRunsResponse;
(function (GetV1MailboxesByMailboxIdSyncRunsResponse) {
    GetV1MailboxesByMailboxIdSyncRunsResponse.Object_ = {
        List: "list",
    };
    let Data;
    (function (Data) {
        let Item;
        (function (Item) {
            Item.Status = {
                Running: "running",
                Completed: "completed",
                SkippedDueToActiveLease: "skipped_due_to_active_lease",
                ReconnectRequired: "reconnect_required",
                DispatchRetryExhausted: "dispatch_retry_exhausted",
                FailedAfterLeaseAcquired: "failed_after_lease_acquired",
                LeaseLost: "lease_lost",
            };
        })(Item = Data.Item || (Data.Item = {}));
    })(Data = GetV1MailboxesByMailboxIdSyncRunsResponse.Data || (GetV1MailboxesByMailboxIdSyncRunsResponse.Data = {}));
})(GetV1MailboxesByMailboxIdSyncRunsResponse || (GetV1MailboxesByMailboxIdSyncRunsResponse = {}));
