// This file was auto-generated by Fern from our API Definition.
export var GetV1MessagesResponse;
(function (GetV1MessagesResponse) {
    GetV1MessagesResponse.Object_ = {
        List: "list",
    };
})(GetV1MessagesResponse || (GetV1MessagesResponse = {}));
