// This file was auto-generated by Fern from our API Definition.
export var PostV1ReplaysResponse;
(function (PostV1ReplaysResponse) {
    PostV1ReplaysResponse.Object_ = {
        Replay: "replay",
    };
    PostV1ReplaysResponse.Status = {
        Queued: "queued",
        Running: "running",
        Completed: "completed",
        Failed: "failed",
        Cancelled: "cancelled",
    };
})(PostV1ReplaysResponse || (PostV1ReplaysResponse = {}));
