// This file was auto-generated by Fern from our API Definition.
export var PostV1MailboxesConnectSessionsResponse;
(function (PostV1MailboxesConnectSessionsResponse) {
    PostV1MailboxesConnectSessionsResponse.Object_ = {
        ConnectSession: "connect_session",
    };
})(PostV1MailboxesConnectSessionsResponse || (PostV1MailboxesConnectSessionsResponse = {}));
