/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f3b745e8685d
 */

import { mailboxesCreateConnectSession } from "../funcs/mailboxes-create-connect-session.js";
import { mailboxesGetById } from "../funcs/mailboxes-get-by-id.js";
import { mailboxesGetObservability } from "../funcs/mailboxes-get-observability.js";
import { mailboxesListSyncRuns } from "../funcs/mailboxes-list-sync-runs.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Mailboxes extends ClientSDK {
  /**
   * Create a mailbox connect session
   */
  async createConnectSession(
    request: models.CreateConnectSessionRequest,
    options?: RequestOptions,
  ): Promise<models.ConnectSession> {
    return unwrapAsync(mailboxesCreateConnectSession(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a mailbox
   */
  async getById(
    request: operations.MailboxesGetRequest,
    options?: RequestOptions,
  ): Promise<models.Mailbox> {
    return unwrapAsync(mailboxesGetById(
      this,
      request,
      options,
    ));
  }

  /**
   * List mailbox sync runs
   */
  async listSyncRuns(
    request: operations.MailboxesListSyncRunsRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.MailboxesListSyncRunsResponse, { cursor: string }>
  > {
    return unwrapResultIterator(mailboxesListSyncRuns(
      this,
      request,
      options,
    ));
  }

  /**
   * Get mailbox observability
   */
  async getObservability(
    request: operations.MailboxesGetObservabilityRequest,
    options?: RequestOptions,
  ): Promise<models.MailboxObservability> {
    return unwrapAsync(mailboxesGetObservability(
      this,
      request,
      options,
    ));
  }
}
