/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ConnectSessionObject = {
  ConnectSession: "connect_session",
} as const;
export type ConnectSessionObject = ClosedEnum<typeof ConnectSessionObject>;

export type ConnectSession = {
  id: string;
  object: ConnectSessionObject;
  connectUrl: string;
  expiresAt: Date;
};

/** @internal */
export const ConnectSessionObject$inboundSchema: z.ZodMiniEnum<
  typeof ConnectSessionObject
> = z.enum(ConnectSessionObject);

/** @internal */
export const ConnectSession$inboundSchema: z.ZodMiniType<
  ConnectSession,
  unknown
> = z.object({
  id: types.string(),
  object: ConnectSessionObject$inboundSchema,
  connectUrl: types.string(),
  expiresAt: types.date(),
});

export function connectSessionFromJSON(
  jsonString: string,
): SafeParseResult<ConnectSession, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConnectSession$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConnectSession' from JSON`,
  );
}
