/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 32bea0d97d2f
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const CreateConnectSessionRequestProvider = {
  Gmail: "gmail",
} as const;
export type CreateConnectSessionRequestProvider = ClosedEnum<
  typeof CreateConnectSessionRequestProvider
>;

export type CreateConnectSessionRequest = {
  provider: CreateConnectSessionRequestProvider;
  tenantExternalId: string;
  mailboxExternalId: string;
  redirectUrl: string;
};

/** @internal */
export const CreateConnectSessionRequestProvider$outboundSchema: z.ZodMiniEnum<
  typeof CreateConnectSessionRequestProvider
> = z.enum(CreateConnectSessionRequestProvider);

/** @internal */
export type CreateConnectSessionRequest$Outbound = {
  provider: string;
  tenantExternalId: string;
  mailboxExternalId: string;
  redirectUrl: string;
};

/** @internal */
export const CreateConnectSessionRequest$outboundSchema: z.ZodMiniType<
  CreateConnectSessionRequest$Outbound,
  CreateConnectSessionRequest
> = z.object({
  provider: CreateConnectSessionRequestProvider$outboundSchema,
  tenantExternalId: z.string(),
  mailboxExternalId: z.string(),
  redirectUrl: z.string(),
});

export function createConnectSessionRequestToJSON(
  createConnectSessionRequest: CreateConnectSessionRequest,
): string {
  return JSON.stringify(
    CreateConnectSessionRequest$outboundSchema.parse(
      createConnectSessionRequest,
    ),
  );
}
