/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateWebhookEndpointRequest = {
  url: string;
  description?: string | null | undefined;
};

/** @internal */
export type CreateWebhookEndpointRequest$Outbound = {
  url: string;
  description?: string | null | undefined;
};

/** @internal */
export const CreateWebhookEndpointRequest$outboundSchema: z.ZodMiniType<
  CreateWebhookEndpointRequest$Outbound,
  CreateWebhookEndpointRequest
> = z.object({
  url: z.string(),
  description: z.optional(z.nullable(z.string())),
});

export function createWebhookEndpointRequestToJSON(
  createWebhookEndpointRequest: CreateWebhookEndpointRequest,
): string {
  return JSON.stringify(
    CreateWebhookEndpointRequest$outboundSchema.parse(
      createWebhookEndpointRequest,
    ),
  );
}
