/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const CreateWebhookEndpointSubscriptionRequestEventType = {
  MessageCreated: "message.created",
  MessageUpdated: "message.updated",
  ThreadUpdated: "thread.updated",
} as const;
export type CreateWebhookEndpointSubscriptionRequestEventType = OpenEnum<
  typeof CreateWebhookEndpointSubscriptionRequestEventType
>;

export type CreateWebhookEndpointSubscriptionRequest = {
  mailboxIds: Array<string>;
  eventTypes: Array<CreateWebhookEndpointSubscriptionRequestEventType>;
};

/** @internal */
export const CreateWebhookEndpointSubscriptionRequestEventType$outboundSchema:
  z.ZodMiniType<string, CreateWebhookEndpointSubscriptionRequestEventType> =
    openEnums.outboundSchema(CreateWebhookEndpointSubscriptionRequestEventType);

/** @internal */
export type CreateWebhookEndpointSubscriptionRequest$Outbound = {
  mailboxIds: Array<string>;
  eventTypes: Array<string>;
};

/** @internal */
export const CreateWebhookEndpointSubscriptionRequest$outboundSchema:
  z.ZodMiniType<
    CreateWebhookEndpointSubscriptionRequest$Outbound,
    CreateWebhookEndpointSubscriptionRequest
  > = z.object({
    mailboxIds: z.array(z.string()),
    eventTypes: z.array(
      CreateWebhookEndpointSubscriptionRequestEventType$outboundSchema,
    ),
  });

export function createWebhookEndpointSubscriptionRequestToJSON(
  createWebhookEndpointSubscriptionRequest:
    CreateWebhookEndpointSubscriptionRequest,
): string {
  return JSON.stringify(
    CreateWebhookEndpointSubscriptionRequest$outboundSchema.parse(
      createWebhookEndpointSubscriptionRequest,
    ),
  );
}
