/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 05623df7fe13
 */

import * as z from "zod/v4-mini";
import {
  WebhookEventType,
  WebhookEventType$outboundSchema,
} from "./webhook-event-type.js";

export type CreateWebhookEndpointSubscriptionRequest = {
  mailboxIds: Array<string>;
  eventTypes: Array<WebhookEventType>;
};

/** @internal */
export type CreateWebhookEndpointSubscriptionRequest$Outbound = {
  mailboxIds: Array<string>;
  eventTypes: Array<string>;
};

/** @internal */
export const CreateWebhookEndpointSubscriptionRequest$outboundSchema:
  z.ZodMiniType<
    CreateWebhookEndpointSubscriptionRequest$Outbound,
    CreateWebhookEndpointSubscriptionRequest
  > = z.object({
    mailboxIds: z.array(z.string()),
    eventTypes: z.array(WebhookEventType$outboundSchema),
  });

export function createWebhookEndpointSubscriptionRequestToJSON(
  createWebhookEndpointSubscriptionRequest:
    CreateWebhookEndpointSubscriptionRequest,
): string {
  return JSON.stringify(
    CreateWebhookEndpointSubscriptionRequest$outboundSchema.parse(
      createWebhookEndpointSubscriptionRequest,
    ),
  );
}
