/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: aa30bcaa4545
 */

import * as z from "zod/v4-mini";

export type CreateReplayRequest = {
  mailboxId: string;
  webhookEndpointId: string;
  startTime: string;
  endTime: string;
};

/** @internal */
export type CreateReplayRequest$Outbound = {
  mailboxId: string;
  webhookEndpointId: string;
  startTime: string;
  endTime: string;
};

/** @internal */
export const CreateReplayRequest$outboundSchema: z.ZodMiniType<
  CreateReplayRequest$Outbound,
  CreateReplayRequest
> = z.object({
  mailboxId: z.string(),
  webhookEndpointId: z.string(),
  startTime: z.string(),
  endTime: z.string(),
});

export function createReplayRequestToJSON(
  createReplayRequest: CreateReplayRequest,
): string {
  return JSON.stringify(
    CreateReplayRequest$outboundSchema.parse(createReplayRequest),
  );
}
