/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const DeliveryState = {
  Healthy: "healthy",
  Degraded: "degraded",
  Failing: "failing",
} as const;
export type DeliveryState = OpenEnum<typeof DeliveryState>;

/** @internal */
export const DeliveryState$inboundSchema: z.ZodMiniType<
  DeliveryState,
  unknown
> = openEnums.inboundSchema(DeliveryState);
