/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5fffef1826a2
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ErrorDetail = {
  code: string;
  message: string;
  occurredAt: Date;
  retryable: boolean;
};

/** @internal */
export const ErrorDetail$inboundSchema: z.ZodMiniType<ErrorDetail, unknown> = z
  .object({
    code: types.string(),
    message: types.string(),
    occurredAt: types.date(),
    retryable: types.boolean(),
  });

export function errorDetailFromJSON(
  jsonString: string,
): SafeParseResult<ErrorDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorDetail' from JSON`,
  );
}
