/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const MailboxObservabilityObject = {
  MailboxObservability: "mailbox_observability",
} as const;
export type MailboxObservabilityObject = ClosedEnum<
  typeof MailboxObservabilityObject
>;

export const LagStatus = {
  Active: "active",
  ReconnectRequired: "reconnect_required",
  Disabled: "disabled",
} as const;
export type LagStatus = OpenEnum<typeof LagStatus>;

export const MailboxObservabilitySyncState = {
  Initializing: "initializing",
  Healthy: "healthy",
  Lagging: "lagging",
  Failed: "failed",
} as const;
export type MailboxObservabilitySyncState = OpenEnum<
  typeof MailboxObservabilitySyncState
>;

export const MailboxObservabilityWatchState = {
  Active: "active",
  Expiring: "expiring",
  Expired: "expired",
  Unhealthy: "unhealthy",
} as const;
export type MailboxObservabilityWatchState = OpenEnum<
  typeof MailboxObservabilityWatchState
>;

export type Lag = {
  status: LagStatus;
  syncState: MailboxObservabilitySyncState;
  watchState: MailboxObservabilityWatchState;
  lastSuccessfulSyncAt: Date | null;
  lagSeconds: number | null;
};

export type Cursor = {
  currentCursor: string | null;
  previousCursor: string | null;
  nextCursor: string | null;
  advanced: boolean | null;
  advancedAt: Date | null;
};

export type Lease = {
  activeLeaseOwner: string | null;
  activeLeaseHeartbeatAt: Date | null;
  activeLeaseExpiresAt: Date | null;
  contentionCount24h: number;
  latestContentionAt: Date | null;
  leaseLossCount24h: number;
  latestLeaseLossAt: Date | null;
};

export const MailboxObservabilityDeliveryState = {
  Healthy: "healthy",
  Degraded: "degraded",
  Failing: "failing",
} as const;
export type MailboxObservabilityDeliveryState = OpenEnum<
  typeof MailboxObservabilityDeliveryState
>;

export type MailboxObservabilityLastDeliveryError = {
  code: string;
  message: string;
  occurredAt: Date;
  retryable: boolean;
};

export type WebhookDelivery = {
  webhookEndpointId: string;
  webhookEndpointUrl: string;
  deliveryState: MailboxObservabilityDeliveryState;
  consecutiveFailures: number;
  pendingDeliveries: number;
  processingDeliveries: number;
  failedDeliveries: number;
  lastDeliveryAt: Date | null;
  lastDeliveryError: MailboxObservabilityLastDeliveryError | null;
};

export const LatestSyncRunStatus = {
  Running: "running",
  Completed: "completed",
  SkippedDueToActiveLease: "skipped_due_to_active_lease",
  ReconnectRequired: "reconnect_required",
  DispatchRetryExhausted: "dispatch_retry_exhausted",
  FailedAfterLeaseAcquired: "failed_after_lease_acquired",
  LeaseLost: "lease_lost",
} as const;
export type LatestSyncRunStatus = OpenEnum<typeof LatestSyncRunStatus>;

export type LatestSyncRun = {
  syncRunId: string;
  mailboxId: string;
  startedAt: Date;
  completedAt: Date | null;
  status: LatestSyncRunStatus;
  detail: string | null;
  eventsEmitted: number | null;
  leaseOwnerId: string | null;
  previousCursor: string | null;
  nextCursor: string | null;
  cursorAdvanced: boolean | null;
};

export type MailboxObservability = {
  object: MailboxObservabilityObject;
  mailboxId: string;
  generatedAt: Date;
  lag: Lag;
  cursor: Cursor;
  lease: Lease;
  webhookDeliveries: Array<WebhookDelivery>;
  latestSyncRun: LatestSyncRun | null;
};

/** @internal */
export const MailboxObservabilityObject$inboundSchema: z.ZodMiniEnum<
  typeof MailboxObservabilityObject
> = z.enum(MailboxObservabilityObject);

/** @internal */
export const LagStatus$inboundSchema: z.ZodMiniType<LagStatus, unknown> =
  openEnums.inboundSchema(LagStatus);

/** @internal */
export const MailboxObservabilitySyncState$inboundSchema: z.ZodMiniType<
  MailboxObservabilitySyncState,
  unknown
> = openEnums.inboundSchema(MailboxObservabilitySyncState);

/** @internal */
export const MailboxObservabilityWatchState$inboundSchema: z.ZodMiniType<
  MailboxObservabilityWatchState,
  unknown
> = openEnums.inboundSchema(MailboxObservabilityWatchState);

/** @internal */
export const Lag$inboundSchema: z.ZodMiniType<Lag, unknown> = z.object({
  status: LagStatus$inboundSchema,
  syncState: MailboxObservabilitySyncState$inboundSchema,
  watchState: MailboxObservabilityWatchState$inboundSchema,
  lastSuccessfulSyncAt: types.nullable(types.date()),
  lagSeconds: types.nullable(types.number()),
});

export function lagFromJSON(
  jsonString: string,
): SafeParseResult<Lag, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Lag$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Lag' from JSON`,
  );
}

/** @internal */
export const Cursor$inboundSchema: z.ZodMiniType<Cursor, unknown> = z.object({
  currentCursor: types.nullable(types.string()),
  previousCursor: types.nullable(types.string()),
  nextCursor: types.nullable(types.string()),
  advanced: types.nullable(types.boolean()),
  advancedAt: types.nullable(types.date()),
});

export function cursorFromJSON(
  jsonString: string,
): SafeParseResult<Cursor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Cursor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Cursor' from JSON`,
  );
}

/** @internal */
export const Lease$inboundSchema: z.ZodMiniType<Lease, unknown> = z.object({
  activeLeaseOwner: types.nullable(types.string()),
  activeLeaseHeartbeatAt: types.nullable(types.date()),
  activeLeaseExpiresAt: types.nullable(types.date()),
  contentionCount24h: types.number(),
  latestContentionAt: types.nullable(types.date()),
  leaseLossCount24h: types.number(),
  latestLeaseLossAt: types.nullable(types.date()),
});

export function leaseFromJSON(
  jsonString: string,
): SafeParseResult<Lease, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Lease$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Lease' from JSON`,
  );
}

/** @internal */
export const MailboxObservabilityDeliveryState$inboundSchema: z.ZodMiniType<
  MailboxObservabilityDeliveryState,
  unknown
> = openEnums.inboundSchema(MailboxObservabilityDeliveryState);

/** @internal */
export const MailboxObservabilityLastDeliveryError$inboundSchema: z.ZodMiniType<
  MailboxObservabilityLastDeliveryError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  occurredAt: types.date(),
  retryable: types.boolean(),
});

export function mailboxObservabilityLastDeliveryErrorFromJSON(
  jsonString: string,
): SafeParseResult<MailboxObservabilityLastDeliveryError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      MailboxObservabilityLastDeliveryError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MailboxObservabilityLastDeliveryError' from JSON`,
  );
}

/** @internal */
export const WebhookDelivery$inboundSchema: z.ZodMiniType<
  WebhookDelivery,
  unknown
> = z.object({
  webhookEndpointId: types.string(),
  webhookEndpointUrl: types.string(),
  deliveryState: MailboxObservabilityDeliveryState$inboundSchema,
  consecutiveFailures: types.number(),
  pendingDeliveries: types.number(),
  processingDeliveries: types.number(),
  failedDeliveries: types.number(),
  lastDeliveryAt: types.nullable(types.date()),
  lastDeliveryError: types.nullable(
    z.lazy(() => MailboxObservabilityLastDeliveryError$inboundSchema),
  ),
});

export function webhookDeliveryFromJSON(
  jsonString: string,
): SafeParseResult<WebhookDelivery, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookDelivery$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookDelivery' from JSON`,
  );
}

/** @internal */
export const LatestSyncRunStatus$inboundSchema: z.ZodMiniType<
  LatestSyncRunStatus,
  unknown
> = openEnums.inboundSchema(LatestSyncRunStatus);

/** @internal */
export const LatestSyncRun$inboundSchema: z.ZodMiniType<
  LatestSyncRun,
  unknown
> = z.object({
  syncRunId: types.string(),
  mailboxId: types.string(),
  startedAt: types.date(),
  completedAt: types.nullable(types.date()),
  status: LatestSyncRunStatus$inboundSchema,
  detail: types.nullable(types.string()),
  eventsEmitted: types.nullable(types.number()),
  leaseOwnerId: types.nullable(types.string()),
  previousCursor: types.nullable(types.string()),
  nextCursor: types.nullable(types.string()),
  cursorAdvanced: types.nullable(types.boolean()),
});

export function latestSyncRunFromJSON(
  jsonString: string,
): SafeParseResult<LatestSyncRun, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LatestSyncRun$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LatestSyncRun' from JSON`,
  );
}

/** @internal */
export const MailboxObservability$inboundSchema: z.ZodMiniType<
  MailboxObservability,
  unknown
> = z.object({
  object: MailboxObservabilityObject$inboundSchema,
  mailboxId: types.string(),
  generatedAt: types.date(),
  lag: z.lazy(() => Lag$inboundSchema),
  cursor: z.lazy(() => Cursor$inboundSchema),
  lease: z.lazy(() => Lease$inboundSchema),
  webhookDeliveries: z.array(z.lazy(() => WebhookDelivery$inboundSchema)),
  latestSyncRun: types.nullable(z.lazy(() => LatestSyncRun$inboundSchema)),
});

export function mailboxObservabilityFromJSON(
  jsonString: string,
): SafeParseResult<MailboxObservability, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MailboxObservability$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MailboxObservability' from JSON`,
  );
}
