/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9f8bbf52c935
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DeliveryState,
  DeliveryState$inboundSchema,
} from "./delivery-state.js";
import { ErrorDetail, ErrorDetail$inboundSchema } from "./error-detail.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  MailboxStatus,
  MailboxStatus$inboundSchema,
} from "./mailbox-status.js";
import { SyncRun, SyncRun$inboundSchema } from "./sync-run.js";
import { SyncState, SyncState$inboundSchema } from "./sync-state.js";
import { WatchState, WatchState$inboundSchema } from "./watch-state.js";

export const MailboxObservabilityObject = {
  MailboxObservability: "mailbox_observability",
} as const;
export type MailboxObservabilityObject = ClosedEnum<
  typeof MailboxObservabilityObject
>;

export type Lag = {
  status: MailboxStatus;
  syncState: SyncState;
  watchState: WatchState;
  lastSuccessfulSyncAt: Date | null;
  lagSeconds: number | null;
};

export type Cursor = {
  currentCursor: string | null;
  previousCursor: string | null;
  nextCursor: string | null;
  advanced: boolean | null;
  advancedAt: Date | null;
};

export type Lease = {
  activeLeaseOwner: string | null;
  activeLeaseHeartbeatAt: Date | null;
  activeLeaseExpiresAt: Date | null;
  contentionCount24h: number;
  latestContentionAt: Date | null;
  leaseLossCount24h: number;
  latestLeaseLossAt: Date | null;
};

export type WebhookDelivery = {
  webhookEndpointId: string;
  webhookEndpointUrl: string;
  deliveryState: DeliveryState;
  consecutiveFailures: number;
  pendingDeliveries: number;
  processingDeliveries: number;
  failedDeliveries: number;
  lastDeliveryAt: Date | null;
  lastDeliveryError: ErrorDetail | null;
};

export type MailboxObservability = {
  object: MailboxObservabilityObject;
  mailboxId: string;
  generatedAt: Date;
  lag: Lag;
  cursor: Cursor;
  lease: Lease;
  webhookDeliveries: Array<WebhookDelivery>;
  latestSyncRun: SyncRun | null;
};

/** @internal */
export const MailboxObservabilityObject$inboundSchema: z.ZodMiniEnum<
  typeof MailboxObservabilityObject
> = z.enum(MailboxObservabilityObject);

/** @internal */
export const Lag$inboundSchema: z.ZodMiniType<Lag, unknown> = z.object({
  status: MailboxStatus$inboundSchema,
  syncState: SyncState$inboundSchema,
  watchState: WatchState$inboundSchema,
  lastSuccessfulSyncAt: types.nullable(types.date()),
  lagSeconds: types.nullable(types.number()),
});

export function lagFromJSON(
  jsonString: string,
): SafeParseResult<Lag, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Lag$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Lag' from JSON`,
  );
}

/** @internal */
export const Cursor$inboundSchema: z.ZodMiniType<Cursor, unknown> = z.object({
  currentCursor: types.nullable(types.string()),
  previousCursor: types.nullable(types.string()),
  nextCursor: types.nullable(types.string()),
  advanced: types.nullable(types.boolean()),
  advancedAt: types.nullable(types.date()),
});

export function cursorFromJSON(
  jsonString: string,
): SafeParseResult<Cursor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Cursor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Cursor' from JSON`,
  );
}

/** @internal */
export const Lease$inboundSchema: z.ZodMiniType<Lease, unknown> = z.object({
  activeLeaseOwner: types.nullable(types.string()),
  activeLeaseHeartbeatAt: types.nullable(types.date()),
  activeLeaseExpiresAt: types.nullable(types.date()),
  contentionCount24h: types.number(),
  latestContentionAt: types.nullable(types.date()),
  leaseLossCount24h: types.number(),
  latestLeaseLossAt: types.nullable(types.date()),
});

export function leaseFromJSON(
  jsonString: string,
): SafeParseResult<Lease, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Lease$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Lease' from JSON`,
  );
}

/** @internal */
export const WebhookDelivery$inboundSchema: z.ZodMiniType<
  WebhookDelivery,
  unknown
> = z.object({
  webhookEndpointId: types.string(),
  webhookEndpointUrl: types.string(),
  deliveryState: DeliveryState$inboundSchema,
  consecutiveFailures: types.number(),
  pendingDeliveries: types.number(),
  processingDeliveries: types.number(),
  failedDeliveries: types.number(),
  lastDeliveryAt: types.nullable(types.date()),
  lastDeliveryError: types.nullable(ErrorDetail$inboundSchema),
});

export function webhookDeliveryFromJSON(
  jsonString: string,
): SafeParseResult<WebhookDelivery, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookDelivery$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookDelivery' from JSON`,
  );
}

/** @internal */
export const MailboxObservability$inboundSchema: z.ZodMiniType<
  MailboxObservability,
  unknown
> = z.object({
  object: MailboxObservabilityObject$inboundSchema,
  mailboxId: types.string(),
  generatedAt: types.date(),
  lag: z.lazy(() => Lag$inboundSchema),
  cursor: z.lazy(() => Cursor$inboundSchema),
  lease: z.lazy(() => Lease$inboundSchema),
  webhookDeliveries: z.array(z.lazy(() => WebhookDelivery$inboundSchema)),
  latestSyncRun: types.nullable(SyncRun$inboundSchema),
});

export function mailboxObservabilityFromJSON(
  jsonString: string,
): SafeParseResult<MailboxObservability, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MailboxObservability$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MailboxObservability' from JSON`,
  );
}
