/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { ErrorDetail, ErrorDetail$inboundSchema } from "./error-detail.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  MailboxStatus,
  MailboxStatus$inboundSchema,
} from "./mailbox-status.js";
import { SyncState, SyncState$inboundSchema } from "./sync-state.js";
import { WatchState, WatchState$inboundSchema } from "./watch-state.js";

export const MailboxObject = {
  Mailbox: "mailbox",
} as const;
export type MailboxObject = ClosedEnum<typeof MailboxObject>;

export const MailboxProvider = {
  Gmail: "gmail",
} as const;
export type MailboxProvider = ClosedEnum<typeof MailboxProvider>;

export type Mailbox = {
  id: string;
  object: MailboxObject;
  provider: MailboxProvider;
  emailAddress: string;
  status: MailboxStatus;
  syncState: SyncState;
  watchState: WatchState;
  initializedAt: Date | null;
  lastSuccessfulSyncAt: Date | null;
  lastError: ErrorDetail | null;
};

/** @internal */
export const MailboxObject$inboundSchema: z.ZodMiniEnum<typeof MailboxObject> =
  z.enum(MailboxObject);

/** @internal */
export const MailboxProvider$inboundSchema: z.ZodMiniEnum<
  typeof MailboxProvider
> = z.enum(MailboxProvider);

/** @internal */
export const Mailbox$inboundSchema: z.ZodMiniType<Mailbox, unknown> = z.object({
  id: types.string(),
  object: MailboxObject$inboundSchema,
  provider: MailboxProvider$inboundSchema,
  emailAddress: types.string(),
  status: MailboxStatus$inboundSchema,
  syncState: SyncState$inboundSchema,
  watchState: WatchState$inboundSchema,
  initializedAt: types.nullable(types.date()),
  lastSuccessfulSyncAt: types.nullable(types.date()),
  lastError: types.nullable(ErrorDetail$inboundSchema),
});

export function mailboxFromJSON(
  jsonString: string,
): SafeParseResult<Mailbox, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Mailbox$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Mailbox' from JSON`,
  );
}
