/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const MailboxObject = {
  Mailbox: "mailbox",
} as const;
export type MailboxObject = ClosedEnum<typeof MailboxObject>;

export const MailboxProvider = {
  Gmail: "gmail",
} as const;
export type MailboxProvider = ClosedEnum<typeof MailboxProvider>;

export const MailboxStatus = {
  Active: "active",
  ReconnectRequired: "reconnect_required",
  Disabled: "disabled",
} as const;
export type MailboxStatus = OpenEnum<typeof MailboxStatus>;

export const MailboxSyncState = {
  Initializing: "initializing",
  Healthy: "healthy",
  Lagging: "lagging",
  Failed: "failed",
} as const;
export type MailboxSyncState = OpenEnum<typeof MailboxSyncState>;

export const MailboxWatchState = {
  Active: "active",
  Expiring: "expiring",
  Expired: "expired",
  Unhealthy: "unhealthy",
} as const;
export type MailboxWatchState = OpenEnum<typeof MailboxWatchState>;

export type LastError = {
  code: string;
  message: string;
  occurredAt: Date;
  retryable: boolean;
};

export type Mailbox = {
  id: string;
  object: MailboxObject;
  provider: MailboxProvider;
  emailAddress: string;
  status: MailboxStatus;
  syncState: MailboxSyncState;
  watchState: MailboxWatchState;
  initializedAt: Date | null;
  lastSuccessfulSyncAt: Date | null;
  lastError: LastError | null;
};

/** @internal */
export const MailboxObject$inboundSchema: z.ZodMiniEnum<typeof MailboxObject> =
  z.enum(MailboxObject);

/** @internal */
export const MailboxProvider$inboundSchema: z.ZodMiniEnum<
  typeof MailboxProvider
> = z.enum(MailboxProvider);

/** @internal */
export const MailboxStatus$inboundSchema: z.ZodMiniType<
  MailboxStatus,
  unknown
> = openEnums.inboundSchema(MailboxStatus);

/** @internal */
export const MailboxSyncState$inboundSchema: z.ZodMiniType<
  MailboxSyncState,
  unknown
> = openEnums.inboundSchema(MailboxSyncState);

/** @internal */
export const MailboxWatchState$inboundSchema: z.ZodMiniType<
  MailboxWatchState,
  unknown
> = openEnums.inboundSchema(MailboxWatchState);

/** @internal */
export const LastError$inboundSchema: z.ZodMiniType<LastError, unknown> = z
  .object({
    code: types.string(),
    message: types.string(),
    occurredAt: types.date(),
    retryable: types.boolean(),
  });

export function lastErrorFromJSON(
  jsonString: string,
): SafeParseResult<LastError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LastError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LastError' from JSON`,
  );
}

/** @internal */
export const Mailbox$inboundSchema: z.ZodMiniType<Mailbox, unknown> = z.object({
  id: types.string(),
  object: MailboxObject$inboundSchema,
  provider: MailboxProvider$inboundSchema,
  emailAddress: types.string(),
  status: MailboxStatus$inboundSchema,
  syncState: MailboxSyncState$inboundSchema,
  watchState: MailboxWatchState$inboundSchema,
  initializedAt: types.nullable(types.date()),
  lastSuccessfulSyncAt: types.nullable(types.date()),
  lastError: types.nullable(z.lazy(() => LastError$inboundSchema)),
});

export function mailboxFromJSON(
  jsonString: string,
): SafeParseResult<Mailbox, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Mailbox$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Mailbox' from JSON`,
  );
}
