/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type From = {
  name: string | null;
  email: string;
};

export type Message = {
  id: string;
  mailboxId: string;
  threadId: string;
  providerMessageId: string;
  subject: string;
  from: From;
  snippet: string;
  receivedAt: Date;
  labelIds: Array<string>;
};

/** @internal */
export const From$inboundSchema: z.ZodMiniType<From, unknown> = z.object({
  name: types.nullable(types.string()),
  email: types.string(),
});

export function fromFromJSON(
  jsonString: string,
): SafeParseResult<From, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => From$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'From' from JSON`,
  );
}

/** @internal */
export const Message$inboundSchema: z.ZodMiniType<Message, unknown> = z.object({
  id: types.string(),
  mailboxId: types.string(),
  threadId: types.string(),
  providerMessageId: types.string(),
  subject: types.string(),
  from: z.lazy(() => From$inboundSchema),
  snippet: types.string(),
  receivedAt: types.date(),
  labelIds: z.array(types.string()),
});

export function messageFromJSON(
  jsonString: string,
): SafeParseResult<Message, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Message$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Message' from JSON`,
  );
}
