/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const ReplayStatus = {
  Queued: "queued",
  Running: "running",
  Completed: "completed",
  Failed: "failed",
  Cancelled: "cancelled",
} as const;
export type ReplayStatus = OpenEnum<typeof ReplayStatus>;

/** @internal */
export const ReplayStatus$inboundSchema: z.ZodMiniType<ReplayStatus, unknown> =
  openEnums.inboundSchema(ReplayStatus);
