/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { ReplayStatus, ReplayStatus$inboundSchema } from "./replay-status.js";

export const ObjectT = {
  Replay: "replay",
} as const;
export type ObjectT = ClosedEnum<typeof ObjectT>;

export type Replay = {
  id: string;
  object: ObjectT;
  status: ReplayStatus;
  mailboxId: string;
  webhookEndpointId: string;
  startTime: Date;
  endTime: Date;
  eventsReplayed: number | null;
  createdAt: Date;
  startedAt: Date | null;
  completedAt: Date | null;
  lastError: string | null;
};

/** @internal */
export const ObjectT$inboundSchema: z.ZodMiniEnum<typeof ObjectT> = z.enum(
  ObjectT,
);

/** @internal */
export const Replay$inboundSchema: z.ZodMiniType<Replay, unknown> = z.object({
  id: types.string(),
  object: ObjectT$inboundSchema,
  status: ReplayStatus$inboundSchema,
  mailboxId: types.string(),
  webhookEndpointId: types.string(),
  startTime: types.date(),
  endTime: types.date(),
  eventsReplayed: types.nullable(types.number()),
  createdAt: types.date(),
  startedAt: types.nullable(types.date()),
  completedAt: types.nullable(types.date()),
  lastError: types.nullable(types.string()),
});

export function replayFromJSON(
  jsonString: string,
): SafeParseResult<Replay, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Replay$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Replay' from JSON`,
  );
}
