/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ReplayObject = {
  Replay: "replay",
} as const;
export type ReplayObject = ClosedEnum<typeof ReplayObject>;

export const Status = {
  Queued: "queued",
  Running: "running",
  Completed: "completed",
  Failed: "failed",
  Cancelled: "cancelled",
} as const;
export type Status = OpenEnum<typeof Status>;

export type Replay = {
  id: string;
  object: ReplayObject;
  status: Status;
  mailboxId: string;
  webhookEndpointId: string;
  startTime: Date;
  endTime: Date;
  eventsReplayed: number | null;
  createdAt: Date;
  startedAt: Date | null;
  completedAt: Date | null;
  lastError: string | null;
};

/** @internal */
export const ReplayObject$inboundSchema: z.ZodMiniEnum<typeof ReplayObject> = z
  .enum(ReplayObject);

/** @internal */
export const Status$inboundSchema: z.ZodMiniType<Status, unknown> = openEnums
  .inboundSchema(Status);

/** @internal */
export const Replay$inboundSchema: z.ZodMiniType<Replay, unknown> = z.object({
  id: types.string(),
  object: ReplayObject$inboundSchema,
  status: Status$inboundSchema,
  mailboxId: types.string(),
  webhookEndpointId: types.string(),
  startTime: types.date(),
  endTime: types.date(),
  eventsReplayed: types.nullable(types.number()),
  createdAt: types.date(),
  startedAt: types.nullable(types.date()),
  completedAt: types.nullable(types.date()),
  lastError: types.nullable(types.string()),
});

export function replayFromJSON(
  jsonString: string,
): SafeParseResult<Replay, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Replay$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Replay' from JSON`,
  );
}
