/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { SyncRun, SyncRun$inboundSchema } from "./sync-run.js";

export const SyncRunListObject = {
  List: "list",
} as const;
export type SyncRunListObject = ClosedEnum<typeof SyncRunListObject>;

export type SyncRunList = {
  object: SyncRunListObject;
  data: Array<SyncRun>;
  nextCursor: string | null;
};

/** @internal */
export const SyncRunListObject$inboundSchema: z.ZodMiniEnum<
  typeof SyncRunListObject
> = z.enum(SyncRunListObject);

/** @internal */
export const SyncRunList$inboundSchema: z.ZodMiniType<SyncRunList, unknown> = z
  .object({
    object: SyncRunListObject$inboundSchema,
    data: z.array(SyncRun$inboundSchema),
    nextCursor: types.nullable(types.string()),
  });

export function syncRunListFromJSON(
  jsonString: string,
): SafeParseResult<SyncRunList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SyncRunList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SyncRunList' from JSON`,
  );
}
