/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const SyncRunStatus = {
  Running: "running",
  Completed: "completed",
  SkippedDueToActiveLease: "skipped_due_to_active_lease",
  ReconnectRequired: "reconnect_required",
  DispatchRetryExhausted: "dispatch_retry_exhausted",
  FailedAfterLeaseAcquired: "failed_after_lease_acquired",
  LeaseLost: "lease_lost",
} as const;
export type SyncRunStatus = OpenEnum<typeof SyncRunStatus>;

/** @internal */
export const SyncRunStatus$inboundSchema: z.ZodMiniType<
  SyncRunStatus,
  unknown
> = openEnums.inboundSchema(SyncRunStatus);
