/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ThreadObject = {
  Thread: "thread",
} as const;
export type ThreadObject = ClosedEnum<typeof ThreadObject>;

export type ThreadMessage = {
  id: string;
  subject: string;
  receivedAt: Date;
};

export type Thread = {
  id: string;
  object: ThreadObject;
  mailboxId: string;
  providerThreadId: string;
  subject: string;
  lastMessageAt: Date;
  messages: Array<ThreadMessage>;
};

/** @internal */
export const ThreadObject$inboundSchema: z.ZodMiniEnum<typeof ThreadObject> = z
  .enum(ThreadObject);

/** @internal */
export const ThreadMessage$inboundSchema: z.ZodMiniType<
  ThreadMessage,
  unknown
> = z.object({
  id: types.string(),
  subject: types.string(),
  receivedAt: types.date(),
});

export function threadMessageFromJSON(
  jsonString: string,
): SafeParseResult<ThreadMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ThreadMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ThreadMessage' from JSON`,
  );
}

/** @internal */
export const Thread$inboundSchema: z.ZodMiniType<Thread, unknown> = z.object({
  id: types.string(),
  object: ThreadObject$inboundSchema,
  mailboxId: types.string(),
  providerThreadId: types.string(),
  subject: types.string(),
  lastMessageAt: types.date(),
  messages: z.array(z.lazy(() => ThreadMessage$inboundSchema)),
});

export function threadFromJSON(
  jsonString: string,
): SafeParseResult<Thread, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Thread$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Thread' from JSON`,
  );
}
