/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8dcb7a111db2
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ThreadListObjectList = {
  List: "list",
} as const;
export type ThreadListObjectList = ClosedEnum<typeof ThreadListObjectList>;

export const ThreadListObjectThread = {
  Thread: "thread",
} as const;
export type ThreadListObjectThread = ClosedEnum<typeof ThreadListObjectThread>;

export type ThreadListData = {
  id: string;
  object: ThreadListObjectThread;
  mailboxId: string;
  providerThreadId: string;
  subject: string;
  lastMessageAt: Date;
};

export type ThreadList = {
  object: ThreadListObjectList;
  data: Array<ThreadListData>;
  nextCursor: string | null;
};

/** @internal */
export const ThreadListObjectList$inboundSchema: z.ZodMiniEnum<
  typeof ThreadListObjectList
> = z.enum(ThreadListObjectList);

/** @internal */
export const ThreadListObjectThread$inboundSchema: z.ZodMiniEnum<
  typeof ThreadListObjectThread
> = z.enum(ThreadListObjectThread);

/** @internal */
export const ThreadListData$inboundSchema: z.ZodMiniType<
  ThreadListData,
  unknown
> = z.object({
  id: types.string(),
  object: ThreadListObjectThread$inboundSchema,
  mailboxId: types.string(),
  providerThreadId: types.string(),
  subject: types.string(),
  lastMessageAt: types.date(),
});

export function threadListDataFromJSON(
  jsonString: string,
): SafeParseResult<ThreadListData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ThreadListData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ThreadListData' from JSON`,
  );
}

/** @internal */
export const ThreadList$inboundSchema: z.ZodMiniType<ThreadList, unknown> = z
  .object({
    object: ThreadListObjectList$inboundSchema,
    data: z.array(z.lazy(() => ThreadListData$inboundSchema)),
    nextCursor: types.nullable(types.string()),
  });

export function threadListFromJSON(
  jsonString: string,
): SafeParseResult<ThreadList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ThreadList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ThreadList' from JSON`,
  );
}
