/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6287d5801c72
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const WatchState = {
  Active: "active",
  Expiring: "expiring",
  Expired: "expired",
  Unhealthy: "unhealthy",
} as const;
export type WatchState = OpenEnum<typeof WatchState>;

/** @internal */
export const WatchState$inboundSchema: z.ZodMiniType<WatchState, unknown> =
  openEnums.inboundSchema(WatchState);
