/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const WebhookEndpointObject = {
  WebhookEndpoint: "webhook_endpoint",
} as const;
export type WebhookEndpointObject = ClosedEnum<typeof WebhookEndpointObject>;

export const WebhookEndpointDeliveryState = {
  Healthy: "healthy",
  Degraded: "degraded",
  Failing: "failing",
} as const;
export type WebhookEndpointDeliveryState = OpenEnum<
  typeof WebhookEndpointDeliveryState
>;

export type WebhookEndpointLastDeliveryError = {
  code: string;
  message: string;
  occurredAt: Date;
  retryable: boolean;
};

export type WebhookEndpoint = {
  id: string;
  object: WebhookEndpointObject;
  url: string;
  description: string | null;
  deliveryState: WebhookEndpointDeliveryState;
  lastDeliveryAt: Date | null;
  lastDeliveryError: WebhookEndpointLastDeliveryError | null;
  createdAt: Date;
  secret: string;
};

/** @internal */
export const WebhookEndpointObject$inboundSchema: z.ZodMiniEnum<
  typeof WebhookEndpointObject
> = z.enum(WebhookEndpointObject);

/** @internal */
export const WebhookEndpointDeliveryState$inboundSchema: z.ZodMiniType<
  WebhookEndpointDeliveryState,
  unknown
> = openEnums.inboundSchema(WebhookEndpointDeliveryState);

/** @internal */
export const WebhookEndpointLastDeliveryError$inboundSchema: z.ZodMiniType<
  WebhookEndpointLastDeliveryError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  occurredAt: types.date(),
  retryable: types.boolean(),
});

export function webhookEndpointLastDeliveryErrorFromJSON(
  jsonString: string,
): SafeParseResult<WebhookEndpointLastDeliveryError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookEndpointLastDeliveryError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookEndpointLastDeliveryError' from JSON`,
  );
}

/** @internal */
export const WebhookEndpoint$inboundSchema: z.ZodMiniType<
  WebhookEndpoint,
  unknown
> = z.object({
  id: types.string(),
  object: WebhookEndpointObject$inboundSchema,
  url: types.string(),
  description: types.nullable(types.string()),
  deliveryState: WebhookEndpointDeliveryState$inboundSchema,
  lastDeliveryAt: types.nullable(types.date()),
  lastDeliveryError: types.nullable(
    z.lazy(() => WebhookEndpointLastDeliveryError$inboundSchema),
  ),
  createdAt: types.date(),
  secret: types.string(),
});

export function webhookEndpointFromJSON(
  jsonString: string,
): SafeParseResult<WebhookEndpoint, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookEndpoint$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookEndpoint' from JSON`,
  );
}
