/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  WebhookEventType,
  WebhookEventType$inboundSchema,
} from "./webhook-event-type.js";

export const WebhookEndpointSubscriptionListObjectList = {
  List: "list",
} as const;
export type WebhookEndpointSubscriptionListObjectList = ClosedEnum<
  typeof WebhookEndpointSubscriptionListObjectList
>;

export const ObjectWebhookEndpointSubscription = {
  WebhookEndpointSubscription: "webhook_endpoint_subscription",
} as const;
export type ObjectWebhookEndpointSubscription = ClosedEnum<
  typeof ObjectWebhookEndpointSubscription
>;

export type WebhookEndpointSubscriptionListData = {
  id: string;
  object: ObjectWebhookEndpointSubscription;
  webhookEndpointId: string;
  mailboxId: string;
  eventTypes: Array<WebhookEventType>;
  createdAt: Date;
};

export type WebhookEndpointSubscriptionList = {
  object: WebhookEndpointSubscriptionListObjectList;
  data: Array<WebhookEndpointSubscriptionListData>;
  nextCursor: string | null;
};

/** @internal */
export const WebhookEndpointSubscriptionListObjectList$inboundSchema:
  z.ZodMiniEnum<typeof WebhookEndpointSubscriptionListObjectList> = z.enum(
    WebhookEndpointSubscriptionListObjectList,
  );

/** @internal */
export const ObjectWebhookEndpointSubscription$inboundSchema: z.ZodMiniEnum<
  typeof ObjectWebhookEndpointSubscription
> = z.enum(ObjectWebhookEndpointSubscription);

/** @internal */
export const WebhookEndpointSubscriptionListData$inboundSchema: z.ZodMiniType<
  WebhookEndpointSubscriptionListData,
  unknown
> = z.object({
  id: types.string(),
  object: ObjectWebhookEndpointSubscription$inboundSchema,
  webhookEndpointId: types.string(),
  mailboxId: types.string(),
  eventTypes: z.array(WebhookEventType$inboundSchema),
  createdAt: types.date(),
});

export function webhookEndpointSubscriptionListDataFromJSON(
  jsonString: string,
): SafeParseResult<WebhookEndpointSubscriptionListData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      WebhookEndpointSubscriptionListData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookEndpointSubscriptionListData' from JSON`,
  );
}

/** @internal */
export const WebhookEndpointSubscriptionList$inboundSchema: z.ZodMiniType<
  WebhookEndpointSubscriptionList,
  unknown
> = z.object({
  object: WebhookEndpointSubscriptionListObjectList$inboundSchema,
  data: z.array(
    z.lazy(() => WebhookEndpointSubscriptionListData$inboundSchema),
  ),
  nextCursor: types.nullable(types.string()),
});

export function webhookEndpointSubscriptionListFromJSON(
  jsonString: string,
): SafeParseResult<WebhookEndpointSubscriptionList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookEndpointSubscriptionList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookEndpointSubscriptionList' from JSON`,
  );
}
